options:
  substitutionOption: 'ALLOW_LOOSE'

substitutions:
  _VITE_GEMINI_API_KEY: ''
  _VITE_FIREBASE_API_KEY: 'AIzaSyBs_MbMSN6BCD1yrZ8SpCoa07DcZm2rmsM'
  _VITE_FIREBASE_AUTH_DOMAIN: 'quimera.ai'
  _VITE_FIREBASE_PROJECT_ID: 'quimeraai'
  _VITE_FIREBASE_STORAGE_BUCKET: 'quimeraai.firebasestorage.app'
  _VITE_FIREBASE_MESSAGING_SENDER_ID: '575386543550'
  _VITE_FIREBASE_APP_ID: '1:575386543550:web:395114b8f43e810a7985ef'
  _VITE_FIREBASE_MEASUREMENT_ID: 'G-KQ26WWK4MD'

steps:
  # Step 1: Build Docker image using Dockerfile.ssr
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.ssr'
      - '-t'
      - 'gcr.io/$PROJECT_ID/quimera-ssr'
      - '--build-arg'
      - 'VITE_GEMINI_API_KEY=${_VITE_GEMINI_API_KEY}'
      - '--build-arg'
      - 'VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}'
      - '--build-arg'
      - 'VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg'
      - 'VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}'
      - '--build-arg'
      - 'VITE_FIREBASE_STORAGE_BUCKET=${_VITE_FIREBASE_STORAGE_BUCKET}'
      - '--build-arg'
      - 'VITE_FIREBASE_MESSAGING_SENDER_ID=${_VITE_FIREBASE_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - 'VITE_FIREBASE_APP_ID=${_VITE_FIREBASE_APP_ID}'
      - '--build-arg'
      - 'VITE_FIREBASE_MEASUREMENT_ID=${_VITE_FIREBASE_MEASUREMENT_ID}'
      - '.'

  # Step 2: Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/quimera-ssr'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'quimera-ssr'
      - '--image'
      - 'gcr.io/$PROJECT_ID/quimera-ssr'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production'

images:
  - 'gcr.io/$PROJECT_ID/quimera-ssr'

timeout: '1800s'
