#!/usr/bin/env python3
"""Fix partial translations: fix Spanish fragments remaining in EN values."""
import json, re, os, sys
sys.stdout.reconfigure(line_buffering=True)

base = '/Users/armandoolmo/QuimeraAppCursor/QuimeraAi'
en_path = os.path.join(base, 'locales', 'en', 'translation.json')
es_path = os.path.join(base, 'locales', 'es', 'translation.json')

with open(en_path, 'r', encoding='utf-8') as f:
    en = json.load(f)
with open(es_path, 'r', encoding='utf-8') as f:
    es = json.load(f)

# Phrase-level replacements for partial translations in EN
PHRASE_FIXES = {
    # Partial fixes from word replacement
    'Name del Chatbot': 'Chatbot Name', 'Name del Widget': 'Widget Name',
    'Name de la Zone': 'Zone Name', 'Name del Tax': 'Tax Name',
    'Name del Bot': 'Bot Name', 'Name de la Palette': 'Palette Name',
    'Settings SEO': 'SEO Settings', 'Settings de': 'Settings of',
    'Users Registered': 'Registered Users',
    'Information Basic': 'Basic Information', 'Information Personal': 'Personal Information',
    'Description SEO': 'SEO Description', 'Description OG': 'OG Description',
    'Image OG': 'OG Image', 'Site Name OG': 'OG Site Name',
    # Spanish particles
    ' del ': ' of the ', ' de la ': ' of the ', ' de las ': ' of the ',
    ' de los ': ' of the ', ' de tu ': ' your ', ' de su ': ' their ',
    ' de un ': ' of a ', ' de una ': ' of a ',
    ' del ': ' of the ', ' al ': ' to the ',
    ' en el ': ' in the ', ' en la ': ' in the ',
    ' en las ': ' in the ', ' en los ': ' in the ',
    ' con el ': ' with the ', ' con la ': ' with the ',
    ' con tu ': ' with your ', ' con los ': ' with the ',
    ' por el ': ' by the ', ' por la ': ' by the ',
    ' para el ': ' for the ', ' para la ': ' for the ',
    ' para tu ': ' for your ', ' para los ': ' for the ',
    ' desde el ': ' from the ', ' desde la ': ' from the ',
    ' sin ': ' without ', ' sobre ': ' about ',
    ' como ': ' as ', ' entre ': ' between ',
    ' cada ': ' each ', ' otro ': ' another ',
    ' mejor ': ' best ', ' más ': ' more ',
    ' este ': ' this ', ' esta ': ' this ',
    ' ese ': ' that ', ' esa ': ' that ',
    ' todo ': ' all ', ' toda ': ' all ',
    ' todos los ': ' all ', ' todas las ': ' all ',
    # Common Spanish patterns
    'Salón de Belleza': 'Beauty Salon',
    'Taller Mecánico': 'Auto Repair Shop',
    'Bar y Discoteca': 'Bar & Nightclub',
    'Concesionario de Autos': 'Car Dealership',
    'Renta de Autos': 'Car Rental',
    'Escuela de Manejo': 'Driving School',
    'Entrega de Comida': 'Food Delivery',
    'Diseño Gráfico': 'Graphic Design',
    'Decoración del Hogar': 'Home Decor',
    'Mejoras del Hogar': 'Home Improvement',
    'Recursos Humanos': 'Human Resources',
    'Diseño de Interiores': 'Interior Design',
    'Escuela de Idiomas': 'Language School',
    'Servicios Legales': 'Legal Services',
    'Marketing y Publicidad': 'Marketing & Advertising',
    'Clínica Médica': 'Medical Clinic',
    'Salud Mental': 'Mental Health',
    'Aplicaciones Móviles': 'Mobile Apps',
    'Servicios de Mudanza': 'Moving Services',
    'Música y Audio': 'Music & Audio',
    'Escuela de Música': 'Music School',
    'Salón de Uñas': 'Nail Salon',
    'Servicios de Limpieza': 'Cleaning Services',
    'Agencia Creativa': 'Creative Agency',
    'Estética Canina': 'Dog Grooming',
    'Servicios Empresariales': 'Business Services',
    'Servicios Financieros': 'Financial Services',
    'Fitness y Gimnasio': 'Fitness & Gym',
    'Galería de Arte': 'Art Gallery',
    'Planificación de Eventos': 'Event Planning',
    'Producción Audiovisual': 'Film Production',
    'Tours de Aventura': 'Adventure Tours',
    'Bed & Breakfast': 'Bed & Breakfast',
    'Comercio Electrónico': 'E-commerce',
    'Medio Ambiente': 'Environment',
    'Bienes Raíces': 'Real Estate',
    'Sin Fines de Lucro': 'Non-profit',
    'Mascotas y Animales': 'Pets & Animals',
    'Agricultura y Medio Ambiente': 'Agriculture & Environment',
    'Automotriz y Transporte': 'Automotive & Transport',
    'Creatividad y Medios': 'Creative & Media',
    'Educación y Capacitación': 'Education & Training',
    'Eventos y Entretenimiento': 'Events & Entertainment',
    'Moda y Belleza': 'Fashion & Beauty',
    'Finanzas y Seguros': 'Finance & Insurance',
    'Alimentos y Hospitalidad': 'Food & Hospitality',
    'Gobierno y Sector Público': 'Government & Public Sector',
    'Salud y Bienestar': 'Health & Wellness',
    'Servicios del Hogar': 'Home Services',
    'Manufactura e Industrial': 'Manufacturing & Industrial',
    'Sin Fines de Lucro y Comunidad': 'Non-profit & Community',
    'Servicios Profesionales': 'Professional Services',
    'Bienes Raíces y Construcción': 'Real Estate & Construction',
    'Retail y Comercio': 'Retail & Commerce',
    'Tecnología y Digital': 'Technology & Digital',
    'Viajes y Turismo': 'Travel & Tourism',
    # Chatbot
    'Agent Personality': 'Agent Personality',
    'Business Profile': 'Business Profile',
    'Tone de Voice': 'Tone of Voice',
    'Voice y En Vivo': 'Voice & Live',
    'En Vivo': 'Live',
    'Captura de Leads': 'Lead Capture',
    'Policies y Contact': 'Policies & Contact',
    # Special patterns 
    'Generador de Images Quimera': 'Quimera Image Generator',
    'Images de Reference': 'Reference Images',
    'Image de Reference': 'Reference Image',
    'Added como reference': 'Added as reference',
    'Prompt Negativo': 'Negative Prompt',
    'All los Projects': 'All Projects',
    'Image Sin Assign': 'Unassigned Images',
    'Controles Vision Pro': 'Vision Pro Controls',
    'potenciado por': 'Powered by',
    'Potenciado por': 'Powered by',
    # Common remaining
    'Intenta': 'Try', 'ajustar': 'adjusting', 'filtros': 'filters',
    'Explora': 'Explore', 'disponibles': 'available', 'encuentra': 'find',
    'ajuste': 'fits', 'industria': 'industry',
    'Presiona': 'Press', 'crear': 'create', 'basado': 'based',
    'textos': 'texts', 'imágenes': 'images', 'colores': 'colors',
    'hacerla': 'make it', 'tuya': 'yours',
    'redirigido': 'redirected', 'personalizar': 'customize',
    'modificar': 'modify',
    'pasa después': 'happens next',
    'Qué pasa': 'What happens',
    'Cómo usar': 'How to use',
    'plantillas': 'templates',
    'previsuales': 'preview', 'secciones': 'sections',
    'incluidas': 'included', 'disponible': 'available',
    'copia': 'copy', 'nuevo proyecto': 'new project',
    # Full phrase replacements
    'Configuración y Perfil': 'Settings & Profile',
    'Zona de Peligro': 'Danger Zone',
    'Eliminar Mi Cuenta': 'Delete My Account',
    'Name para Show': 'Display Name',
    'Nombre para Mostrar': 'Display Name',
    'Vote de Back': 'Go Back',
    'Cambiar Foto': 'Change Photo',
    'Confirm Deletion': 'Confirm Deletion',
    'Guardar Cambios': 'Save Changes',
    'Confirma con tu password': 'Confirm with your password',
    'Edit Profile': 'Edit Profile',
    'Limpiar Todo': 'Clear All',
    'Aplicar Todo': 'Apply All',
    'Sugerir con IA': 'Suggest with AI',
    'Sugerencias de IA basadas en colores': 'AI suggestions based on colors',
    'Importar paleta de Coolors.co': 'Import palette from Coolors.co',
    'Paletas Predefinidas': 'Preset Palettes',
    'Colores Personalizados': 'Custom Colors',
    'Fuentes Globales': 'Global Fonts',
    'Títulos / Headings': 'Headings / Titles',
    'Botones / UI': 'Buttons / UI',
    'Pega URL de coolors.co o los colores...': 'Paste Coolors.co URL or colors...',
    'Color inválido para:': 'Invalid color for:',
    'Necesitas al menos 3 colores para generar una paleta': 'You need at least 3 colors to generate a palette',
    'No se detectaron colores válidos. Asegúrate de pegar una URL de Coolors.co': 'No valid colors detected. Make sure to paste a Coolors.co URL',
    'No hay un proyecto activo': 'No active project',
    'Ejemplos de formato aceptado:': 'Accepted format examples:',
    'Importar desde Coolors.co': 'Import from Coolors.co',
    'La respuesta de AI no contiene JSON válido': 'AI response does not contain valid JSON',
    'Gestor de Contenidos': 'Content Manager',
    'Crear con IA': 'Create with AI',
    'Ordenar por Fecha': 'Sort by Date',
    'Esta Semana': 'This Week',
    'Todo el Tiempo': 'All Time',
    'Total de Publicaciones': 'Total Posts',
    'Agregar Elemento': 'Add Item',
    'Agregar Estadística': 'Add Statistic',
    'Texto Alternativo': 'Alt Text',
    'Imagen de Fondo': 'Background Image',
    'Texto de Insignia': 'Badge Text',
    'Audaz y Dinámico': 'Bold & Dynamic',
    'Estilo de Borde': 'Border Style',
    'Abajo Izquierda': 'Bottom Left',
    'Abajo Derecha': 'Bottom Right',
    'Sombra de Caja': 'Box Shadow',
    'Estilo de Botón': 'Button Style',
    'Texto del Botón': 'Button Text',
    'Cerrar panel de propiedades': 'Close properties panel',
    'Espacio de Columnas': 'Column Gap',
    'Duplicar Elemento': 'Duplicate Item',
    'Editar Elemento': 'Edit Item',
    'Tiempo estimado restante:': 'Estimated time remaining:',
    'Algunas imágenes no pudieron generarse': 'Some images could not be generated',
    'Puedes generarlas después desde el editor': 'You can generate them later from the editor',
    'Generando imágenes': 'Generating images',
    'Creando imágenes únicas para tu sitio web...': 'Creating unique images for your website...',
    'imágenes generadas': 'images generated',
    'Imagen pendiente': 'Pending image',
    'Esta imagen no pudo generarse automáticamente. Puedes generarla después desde el editor.': 'This image could not be generated automatically. You can generate them later from the editor.',
    'Todos los Proyectos': 'All Projects',
    'Biblioteca de Recursos': 'Asset Library',
    'Recursos Sin Asignar': 'Unassigned Assets',
    'Imágenes Sin Asignar': 'Unassigned Images',
    'Mi Biblioteca': 'My Library',
    'Biblioteca Global': 'Global Library',
    'Buscar recursos...': 'Search assets...',
    'Seleccionar de Biblioteca': 'Select from Library',
    'Información del Archivo': 'File Information',
    'Vista previa no disponible para este tipo de archivo': 'Preview not available for this file type',
    'Notas guardadas': 'Notes saved',
    'Generar Resumen': 'Generate Summary',
    'Clic para seleccionar': 'Click to select',
    'Doble clic para ver detalles': 'Double click to view details',
    'Crea imágenes impresionantes con IA y controles avanzados': 'Create stunning images with AI and advanced controls',
    'Generador de Imágenes Quimera': 'Quimera Image Generator',
    'Haz clic para subir o arrastra desde la biblioteca': 'Click to upload or drag from library',
    'Hasta 14 imágenes • Arrastra imágenes de tus recursos': 'Up to 14 images • Drag images from your assets',
    '¡Descripción mejorada!': 'Prompt enhanced!',
    '¡Imagen generada exitosamente!': 'Image generated successfully!',
    'Generación fallida. Revisa los detalles en la consola.': 'Generation failed. Check details in the console.',
    'Imagen añadida como referencia': 'Image added as reference',
    'Esta imagen ya está añadida como referencia': 'This image is already added as reference',
    'No se puede añadir esta imagen. Por favor súbela desde tu computadora usando el botón de subir.': 'Cannot add this image. Please upload it from your computer using the upload button.',
    'Máximo 14 imágenes de referencia permitidas': 'Maximum 14 reference images allowed',
    'Imágenes de Referencia (Opcional)': 'Reference Images (Optional)',
    'Añadir como imagen de referencia': 'Add as reference image',
    'Arrastra para usar como referencia • Doble clic para ver': 'Drag to use as reference • Double click to view',
    # Superadmin controls
    'Estilo póster de película con degradado y mayúsculas': 'Movie poster style with gradient and uppercase',
    '🔤 Título gigante en negrita con superposición de color': '🔤 Giant bold title with color overlay',
    'Estilo revista con título anclado abajo a la izquierda': 'Magazine style with title anchored bottom left',
    # SEO
    'Configuración de Bots de IA': 'AI Bot Settings',
    'Optimización de Bots de IA': 'AI Bot Optimization',
    'Rastreabilidad de IA': 'AI Crawlability',
    'Optimización IA': 'AI Optimization',
    'Descripción Optimizada para IA': 'AI Optimized Description',
    'Motores de Búsqueda de IA': 'AI Search Engines',
    'Permitir Rastreo de IA': 'Allow AI Crawling',
    'Habilita que los bots de IA rastreen e indexen tu sitio': 'Allow AI bots to crawl and index your site',
    'Tu nombre o empresa': 'Your name or company',
    'Información Básica': 'Basic Information',
    'Verificación de Sitio Bing': 'Bing Site Verification',
    'Una breve descripción de tu sitio web...': 'A brief description of your website...',
    'URL Canónica': 'Canonical URL',
    'Tipo de Tarjeta': 'Card Type',
    'caracteres (recomendado)': 'characters (recommended)',
    'Crear Proyecto': 'Create Project',
    'Crea un nuevo proyecto para comenzar a configurar SEO': 'Create a new project to start configuring SEO',
    'Verificación de Sitio Google': 'Google Site Verification',
    'Indexar, Seguir (Recomendado)': 'Index, Follow (Recommended)',
    'Indexar, No Seguir': 'Index, No Follow',
    'Temas Clave (separados por comas)': 'Key Topics (comma separated)',
    'Ayuda a la IA a categorizar y entender los temas principales de tu sitio web': 'Helps AI categorize and understand the main topics of your website',
    'IA, Aprendizaje Automático, Desarrollo Web, SaaS': 'AI, Machine Learning, Web Development, SaaS',
    'Palabras Clave': 'Keywords',
    'Palabras Clave (separadas por comas)': 'Keywords (comma separated)',
    'diseño web, IA, automatización': 'web design, AI, automation',
    'Deja vacío para usar': 'Leave empty to use',
    'Deja vacío para usar la meta descripción': 'Leave empty to use the meta description',
    'Deja vacío para usar el título de la página': 'Leave empty to use the page title',
    'Cargando configuración SEO...': 'Loading SEO settings...',
    'Negocio Local': 'Local Business',
    'Meta Descripción': 'Meta Description',
    'Mi Sitio Web Increíble': 'My Amazing Website',
    'No Indexar, Seguir': 'No Index, Follow',
    'No Indexar, No Seguir': 'No Index, No Follow',
    'No hay proyectos disponibles': 'No projects available',
    'Descripción OG': 'OG Description',
    'URL de Imagen OG': 'OG Image URL',
    'Nombre del Sitio OG': 'OG Site Name',
    'Organización': 'Organization', 'Título de la Página': 'Page Title',
    'Reproductor': 'Player',
    'Recomendado: 1200x630px': 'Recommended: 1200x630px',
    'Etiqueta Meta Robots': 'Robots Meta Tag',
    'Tipo de Schema': 'Schema Type',
    'Elige un proyecto': 'Choose a project',
    'Verificación de Sitio': 'Site Verification',
    'Datos Estructurados (Schema.org)': 'Structured Data (Schema.org)',
    'Optimiza tu sitio web para motores de búsqueda y bots de IA': 'Optimize your website for search engines and AI bots',
    'Resumen con Imagen Grande': 'Summary with Large Image',
    'Configuración SEO': 'SEO Settings',
    'Creador de Twitter (@usuario)': 'Twitter Creator (@username)',
    'URL de Imagen de Twitter': 'Twitter Image URL',
    'Sitio de Twitter (@usuario)': 'Twitter Site (@username)',
    'Actualizado': 'Updated', 'código de verificación': 'verification code',
    'Nombre de tu sitio': 'Your site name',
    #Chatbot
    'Nombre del Chatbot': 'Chatbot Name',
    'Haz clic para subir o arrastra y suelta': 'Click to upload or drag and drop',
    'Estado de Configuración': 'Configuration Status',
    'Desactivado': 'Disabled', 'Preguntas Frecuentes': 'FAQ',
    'Documentos de Conocimiento': 'Knowledge Documents',
    'Captura de Leads': 'Lead Capture', 'Simulador En Vivo': 'Live Simulator',
    'Voz En Vivo': 'Live Voice', 'No se han agregado FAQs': 'No FAQs added',
    'Resumen de Rendimiento': 'Performance Overview',
    'Políticas y Contacto': 'Policies & Contact',
    'Productos y Servicios': 'Products & Services',
    'Tono de Voz': 'Tone of Voice', 'Voz y En Vivo': 'Voice & Live',
    'Color del Widget': 'Widget Color', 'Posición del Widget': 'Widget Position',
    'PDF, Texto, Markdown, CSV, HTML (Máx 10MB)': 'PDF, Text, Markdown, CSV, HTML (Max 10MB)',
    'Perfil del Negocio': 'Business Profile',
    'Personalidad del Agente': 'Agent Personality',
    'Agregar FAQ': 'Add FAQ',
    'Agrega preguntas frecuentes para ayudar a tu chatbot a proporcionar respuestas instantáneas': 'Add frequently asked questions to help your chatbot provide instant answers',
    # Post editor
    'Encabezado 1': 'Heading 1', 'Encabezado 2': 'Heading 2',
    'Encabezado 3': 'Heading 3', 'Insertar Imagen': 'Insert Image',
    'Insertar Enlace': 'Insert Link', 'Insertar Tabla': 'Insert Table',
    'Texto Normal': 'Normal Text', 'Lista Numerada': 'Numbered List',
    'Quitar Enlace': 'Remove Link', 'Descripción SEO': 'SEO Description',
    'Configuración SEO': 'SEO Settings',
    # Profile
    'Cambiar Foto': 'Change Photo', 'Confirmar Eliminación': 'Confirm Deletion',
    'Confirma con tu contraseña': 'Confirm with your password',
    'Zona de Peligro': 'Danger Zone', 'Eliminar Mi Cuenta': 'Delete My Account',
    'Una vez que elimines tu cuenta, no hay vuelta atrás. Por favor, asegúrate.': 'Once you delete your account, there is no going back. Please be sure.',
    'Nombre para Mostrar': 'Display Name', 'Editar Perfil': 'Edit Profile',
    'Contraseña incorrecta. Por favor intenta de nuevo.': 'Incorrect password. Please try again.',
    'Guardar Cambios': 'Save Changes', 'Configuración y Perfil': 'Settings & Profile',
    # Image Picker
    'Creando obra maestra...': 'Creating masterpiece...',
    'Descripción mejorada': 'Prompt enhanced',
    'Usa IA para mejorar tu descripción': 'Use AI to enhance your prompt',
    'Filtrar por Proyecto': 'Filter by Project',
    'Generar Imagen': 'Generate Image',
    'Imagen generada exitosamente': 'Image generated successfully',
    'Imagen generada aplicada': 'Generated image applied',
    'Imagen seleccionada': 'Image selected',
    'Mis Subidas': 'My Uploads',
    'Prompt Negativo': 'Negative Prompt',
    'No hay imágenes globales disponibles.': 'No global images available.',
    'Sin imagen seleccionada': 'No image selected',
    'Abrir Biblioteca / Subir': 'Open Library / Upload',
    'Potenciado por Quimera.ai': 'Powered by Quimera.ai',
    'Modelo Quimera': 'Quimera Model',
    'Buscar imágenes...': 'Search images...',
    'Mostrar proyecto actual': 'Show current project',
    'Intenta ajustar tu búsqueda o filtros': 'Try adjusting your search or filters',
    'Error al subir archivo': 'Error uploading file',
    'Sube una ahora': 'Upload one now',
    'Usar Esta Imagen': 'Use This Image',
    'Controles Vision Pro': 'Vision Pro Controls',
    # Components
    'Pie de página': 'Footer',
    'Llamada a la Acción': 'Call to Action',
    # User templates
    'Plantillas disponibles': 'Available Templates',
    'Creando tu sitio...': 'Creating your site...',
    '¿Cómo usar las plantillas?': 'How to use templates?',
    'Secciones incluidas': 'Sections included',
    'Se creará una copia de esta plantilla como tu nuevo proyecto': 'A copy of this template will be created as your new project',
    'Serás redirigido al editor para personalizar tu sitio': 'You will be redirected to the editor to customize your site',
    'Podrás modificar textos, colores, imágenes y más': 'You can modify texts, colors, images and more',
    'No se encontraron plantillas': 'No templates found',
    'Vista previa': 'Preview',
    'Explora las plantillas disponibles y encuentra una que se ajuste a tu industria': 'Explore available templates and find one that fits your industry',
    'Haz clic en una plantilla para ver la vista previa con todos los detalles': 'Click on a template to view the preview with full details',
    'Presiona "Usar esta plantilla" para crear tu sitio web basado en ella': 'Press "Use this template" to create your website based on it',
    'Personaliza colores, textos e imágenes en el editor para hacerla tuya': 'Customize colors, texts, and images in the editor to make it yours',
    'Intenta ajustar los filtros de búsqueda': 'Try adjusting search filters',
    '¿Qué pasa después?': 'What happens next?',
    # Store Auth
    'Agregar Dirección': 'Add Address',
    'Las direcciones de tus pedidos se guardarán aquí': 'Addresses from your orders will be saved here',
    'Direcciones': 'Addresses', 'Volver al login': 'Back to login',
    'Confirmar Contraseña': 'Confirm Password',
    'Eliminar Cuenta': 'Delete Account',
    'Esta acción no se puede deshacer. Se eliminarán todos tus datos.': 'This action cannot be undone. All your data will be deleted.',
    'de descuento en compras': 'discount on purchases',
    'tu@email.com': 'your@email.com',
    'Ha ocurrido un error': 'An error occurred',
    'El nombre es requerido': 'Name is required',
    'Las contraseñas no coinciden': "Passwords don't match",
    'La contraseña debe tener al menos 6 caracteres': 'Password must be at least 6 characters',
    'Te enviaremos un enlace para restablecer tu contraseña': "We'll send you a link to reset your password",
    'Recuperar Contraseña': 'Recover Password',
    'Iniciar sesión': 'Log in',
    'Accede a tu cuenta en {{storeName}}': 'Access your account at {{storeName}}',
    'Inicia sesión para ver tu cuenta': 'Log in to view your account',
    'Preferencias de Marketing': 'Marketing Preferences',
    'Miembro desde': 'Member since',
    'Beneficios de {{role}}': '{{role}} Benefits',
    'Mis Pedidos': 'My Orders',
    'No tienes direcciones guardadas': 'No saved addresses',
    'No has iniciado sesión': 'Not logged in',
    'Se ha enviado un email para restablecer tu contraseña': 'Password reset email has been sent',
    'Información Personal': 'Personal Information',
    'Recibir emails promocionales': 'Receive promotional emails',
    'Ofertas exclusivas y novedades': 'Exclusive offers and news',
    'Únete a {{storeName}}': 'Join {{storeName}}',
    'Enviar Email': 'Send Email', 'Direcciones Guardadas': 'Saved Addresses',
    'Lista de Deseos': 'Wishlist', 'Estadísticas de Cuenta': 'Account Stats',
    # Store Users
    'Bloquear Usuario': 'Ban User',
    '¿Estás seguro de que deseas bloquear a este usuario? No podrá acceder a su cuenta.': 'Are you sure you want to ban this user? They will not be able to access their account.',
    'Cambiar Rol': 'Change Role', 'Cambiar Estado': 'Change Status',
    'Limpiar filtros': 'Clear filters', 'Confirmar Bloqueo': 'Confirm Ban',
    'Crea segmentos para organizar tus usuarios': 'Create segments to organize your users',
    'Crear Segmento': 'Create Segment', 'Eliminar Segmento': 'Delete Segment',
    '¿Estás seguro de que deseas eliminar este segmento? Los usuarios asignados perderán este segmento.': 'Are you sure you want to delete this segment? Assigned users will lose this segment.',
    'Filtrar por rol': 'Filter by role', 'Filtrar por estado': 'Filter by status',
    'Notas Internas': 'Internal Notes', 'Último acceso': 'Last login',
    'Nuevo Segmento': 'New Segment', 'Nuevos este mes': 'New this month',
    'No hay actividad registrada': 'No registered activity',
    'No hay segmentos creados': 'No segments created',
    'No hay usuarios registrados': 'No registered users',
    'No se encontraron usuarios': 'No users found',
    'en todas las compras': 'on all purchases',
    'Email de recuperación enviado': 'Recovery email sent',
    'Productos exclusivos': 'Exclusive products',
    'Solicitar cotizaciones': 'Request quotes',
    'Ver precios mayoristas': 'View wholesale prices',
    'Configuración de Roles': 'Roles Configuration',
    'Descripción opcional': 'Optional description',
    'Ej: Clientes frecuentes': 'E.g: Frequent customers',
    'Segmentos de Usuarios': 'User Segments',
    'Usuarios Registrados': 'Registered Users',
    'usuarios en tu tienda': 'users in your store',
    'Intenta con otros filtros': 'Try different filters',
    'Detalles del Usuario': 'User Details',
    'Los usuarios que se registren aparecerán aquí': 'Users who register will appear here',
    'Pedidos para VIP': 'Orders for VIP',
    'Gasto para VIP': 'Spending for VIP',
    # Leads
    'Agregar Nuevo Campo': 'Add New Field',
    'Los campos personalizados estarán disponibles al editar leads.': 'Custom fields will be available when editing leads.',
    'Campos Existentes': 'Existing Fields',
    'Plantillas por Industria': 'Industry Templates',
    'Aplica campos pre-configurados para tu industria en un solo click': 'Apply pre-configured fields for your industry in one click',
    'No hay campos personalizados configurados': 'No custom fields configured',
    'Campos Personalizados': 'Custom Fields',
    'Editar Contacto': 'Edit Contact',
    'Los {{count}} leads filtrados están seleccionados.': 'All {{count}} filtered leads are selected.',
    'Seleccionar los {{count}} leads filtrados': 'Select all {{count}} filtered leads',
    # onboardingWizard remaining
    'Preguntas Frecuentes (FAQ)': 'Frequently Asked Questions (FAQ)',
    'Industria / Nicho': 'Industry / Niche',
    'Ofertas Clave': 'Key Offerings',
    'Lista tus mejores servicios o productos...': 'List your best services or products...',
    'Descripción breve': 'Brief description',
    'Nombre del producto/servicio': 'Product/service name',
    'Precio (opcional, ej. $99/mes)': 'Price (optional, e.g. $99/mo)',
    'Agrega tus productos o servicios principales (opcional)': 'Add your main products or services (optional)',
    'Resumen Corto': 'Short Summary',
    'Redes Sociales (Opcional)': 'Social Media (Optional)',
    'Propuesta de Valor Única': 'Unique Value Proposition',
    '¿Qué hace a tu negocio único?': 'What makes your business unique?',
    'URL de {platform}': '{platform} URL',
    'Años en el Negocio (Opcional)': 'Years in Business (Optional)',
    'ej. 5 años, Desde 2019': 'e.g. 5 years, Since 2019',
    'Código Postal': 'Zip Code',
    'ej. Diseño de Interiores, SaaS, Cafetería': 'e.g. Interior Design, SaaS, Cafe',
    '¿Qué hace tu negocio?': 'What does your business do?',
    'Público Objetivo': 'Target Audience',
    'ej. Startups, Propietarios de viviendas...': 'e.g. Startups, Homeowners...',
    'ej. Innovación, Calidad, Integridad...': 'e.g. Innovation, Quality, Integrity...',
    'Cambiar Miniatura': 'Change Thumbnail',
    'Abrir Proyecto': 'Open Project',
    'Acciones del proyecto': 'Project actions',
    'Abrir {{name}}': 'Open {{name}}',
    'Menú de opciones del proyecto': 'Project options menu',
    'Seleccionar {{name}}': 'Select {{name}}',
    '¿Eliminar "{{name}}" permanentemente?': 'Delete "{{name}}" permanently?',
    '¿Eliminar esta plantilla de tu vista?': 'Remove this template from your view?',
}

# Also handle remaining EN patterns in ES file
EN_PHRASE_FIXES = {
    'Analysis Complete!': '¡Análisis Completo!',
    'Analyzing...': 'Analizando...',
    'Analyzing your business...': 'Analizando tu negocio...',
    'Brand Analysis': 'Análisis de Marca',
    'Business Hours': 'Horario de Atención',
    'Announcement Bar': 'Barra de Anuncio',
    'Call to Action': 'Llamada a la Acción',
    'Hero Section': 'Sección Hero',
    'How It Works': 'Cómo Funciona',
    'Recently Viewed': 'Vistos Recientemente',
    'Sale Countdown': 'Cuenta Regresiva',
    'Trust Badges': 'Insignias de Confianza',
    'Already have a website?': '¿Ya tienes un sitio web?',
    "Let's start with your business": 'Comencemos con tu negocio',
    'Tell us about your business so we can create the perfect website.': 'Cuéntanos sobre tu negocio para crear el sitio web perfecto.',
    'Your Business': 'Tu Negocio',
    'Describe your business': 'Describe tu negocio',
    'Tell visitors what makes your business special.': 'Cuéntale a los visitantes qué hace especial a tu negocio.',
    'What do you offer? Let AI suggest or add your own.': '¿Qué ofreces? Deja que la IA sugiera o agrega los tuyos.',
    'Choose Your Template': 'Elige tu Plantilla',
    'AI recommends the best template for your industry.': 'La IA recomienda la mejor plantilla para tu industria.',
    'How can customers reach you? (All fields optional)': '¿Cómo pueden contactarte los clientes? (Todos los campos opcionales)',
    'Change Language': 'Cambiar Idioma',
    'Auto-scroll': 'Auto-desplazamiento',
    'Try Different URL': 'Intentar con Otra URL',
    'Please enter a website URL': 'Por favor ingresa una URL de sitio web',
    'Please try again.': 'Por favor intenta de nuevo.',
    'A short catchy phrase for your business': 'Una frase corta y pegadiza para tu negocio',
    'AI-powered website builder': 'Constructor de sitios web con IA',
    'Redirecting to editor...': 'Redirigiendo al editor...',
    'Brief description (optional)': 'Descripción breve (opcional)',
    'services added': 'servicios agregados',
    'Set up your store': 'Configura tu tienda',
    'Digital (Downloads/Services)': 'Digital (Descargas/Servicios)',
    'International Shipping': 'Envío Internacional',
    'State/Province': 'Estado/Provincia',
    'Sell products online?': '¿Vendes productos en línea?',
    'We will include a store in your website': 'Incluiremos una tienda en tu sitio web',
    'This may take a few minutes. Please wait...': 'Esto puede tomar unos minutos. Por favor espera...',
    'Product Categories': 'Categorías de Productos',
    'Product type': 'Tipo de producto',
    'Select your industry': 'Selecciona tu industria',
    'Search industries...': 'Buscar industrias...',
    'No industries found': 'No se encontraron industrias',
    'No services yet': 'Aún no hay servicios',
    'No templates available': 'No hay plantillas disponibles',
    'Generating Content': 'Generando Contenido',
    'Creating Website': 'Creando Sitio Web',
    'Generating Images': 'Generando Imágenes',
    'Preset Palettes': 'Paletas Predefinidas',
    'Estimated time remaining:': 'Tiempo estimado restante:',
    'Some images could not be generated': 'Algunas imágenes no pudieron generarse',
    'You can generate them later from the editor': 'Puedes generarlas después desde el editor',
    'Generating images': 'Generando imágenes',
    'Creating unique images for your website...': 'Creando imágenes únicas para tu sitio web...',
    'images generated': 'imágenes generadas',
    'Screenshot Carousel': 'Carrusel de Capturas',
    'Gradient Hero': 'Hero con Degradado',
    'Modern Hero': 'Hero Moderno',
    'Sticky header': 'Encabezado fijo',
    'Transparent header': 'Encabezado transparente',
    'Unsaved changes': 'Cambios sin guardar',
    'Section disabled': 'Sección deshabilitada',
    'Section enabled': 'Sección habilitada',
    'Change Logo': 'Cambiar Logo',
    'Copyright Text': 'Texto de Copyright',
    'Button Texts': 'Textos de Botones',
    'CTA Buttons': 'Botones CTA',
    'Highlight popular plan': 'Resaltar plan popular',
    'Primary Button': 'Botón Primario',
    'Secondary Button': 'Botón Secundario',
    "Pricing plans are managed from the Subscriptions panel.": 'Los planes de precio se gestionan desde el panel de Suscripciones.',
    'Total Tenants': 'Total de Inquilinos',
    'Testimonials': 'Testimonios',
}

fixed_en = 0
fixed_es = 0

def fix_en_phrases(d, path=''):
    global fixed_en
    for key in list(d.keys()):
        full = f'{path}.{key}' if path else key
        v = d[key]
        if isinstance(v, dict):
            fix_en_phrases(v, full)
        elif isinstance(v, str) and v in PHRASE_FIXES:
            d[key] = PHRASE_FIXES[v]
            fixed_en += 1

def fix_es_phrases(d, path=''):
    global fixed_es
    for key in list(d.keys()):
        full = f'{path}.{key}' if path else key
        v = d[key]
        if isinstance(v, dict):
            fix_es_phrases(v, full)
        elif isinstance(v, str) and v in EN_PHRASE_FIXES:
            d[key] = EN_PHRASE_FIXES[v]
            fixed_es += 1

fix_en_phrases(en)
fix_es_phrases(es)

with open(en_path, 'w', encoding='utf-8') as f:
    json.dump(en, f, ensure_ascii=False, indent=2)
    f.write('\n')
with open(es_path, 'w', encoding='utf-8') as f:
    json.dump(es, f, ensure_ascii=False, indent=2)
    f.write('\n')

print(f'✅ Fixed {fixed_en} EN values (phrase-level ES→EN)')
print(f'✅ Fixed {fixed_es} ES values (phrase-level EN→ES)')
print(f'✅ Total: {fixed_en + fixed_es}')
