import type {
    BusinessCapability,
    ComponentBuilder,
    ComponentDataAccess,
    ComponentDataRequirement,
    ComponentId,
    ComponentImplementationStatus,
    ComponentRegistryEntry,
    ComponentRegistryFamily,
    ConversionRole,
    MobilePriority,
    PageIntent,
    RecommendedPosition,
    VisualDensity,
} from '../types/componentRegistry';

const commonSources = ['userPrompt', 'businessBlueprint', 'websitePlan', 'existingWebsitePlan'];
const commerceSources = ['businessBlueprint', 'ecommerceBlueprint', 'storefrontBlueprint', 'ecommerceEngine'];
const bioPageSources = ['businessBlueprint', 'bioPageBlueprint', 'bioPageEngine'];

const access = (
    reads: string[],
    canonicalSystem: ComponentDataAccess['canonicalSystem'] = 'business-blueprint',
    presentationOwner: ComponentDataAccess['presentationOwner'] = 'website-builder',
): ComponentDataAccess => ({
    reads,
    writes: [],
    canonicalSystem,
    presentationOwner,
});

const data = (
    key: string,
    label: string,
    source: string,
    minCount = 1,
    required = true,
    mustBeMerchantApproved = false,
): ComponentDataRequirement => ({
    key,
    label,
    source,
    minCount,
    required,
    mustBeMerchantApproved,
});

const entry = (input: {
    id: ComponentId;
    label: string;
    description: string;
    family: ComponentRegistryFamily;
    implementationStatus?: ComponentImplementationStatus;
    visualSupportNotes?: string;
    compatibleBuilders?: ComponentBuilder[];
    compatibleIndustries?: string[];
    incompatibleIndustries?: string[];
    pageIntents?: PageIntent[];
    conversionRoles?: ConversionRole[];
    requiredModules?: BusinessCapability[];
    optionalModules?: BusinessCapability[];
    dataRequirements?: ComponentDataRequirement[];
    minDataRequired?: Record<string, number>;
    recommendedPosition?: RecommendedPosition;
    mobilePriority?: MobilePriority;
    visualDensity?: VisualDensity;
    allowedSources?: string[];
    requiredPlan?: string;
    requiredFeature?: string;
    fallbackComponentId?: ComponentId;
    selectionGuidance?: string[];
    antiPatterns?: string[];
    confidenceThreshold?: number;
    aiSelection?: ComponentRegistryEntry['aiSelection'];
    dataAccess?: ComponentDataAccess;
    renderTargets?: ComponentRegistryEntry['renderTargets'];
}): ComponentRegistryEntry => ({
    compatibleBuilders: ['website'],
    implementationStatus: 'rendered',
    compatibleIndustries: ['all'],
    incompatibleIndustries: [],
    pageIntents: ['website_home'],
    conversionRoles: ['awareness'],
    requiredModules: [],
    optionalModules: [],
    dataRequirements: [],
    minDataRequired: {},
    recommendedPosition: 'middle',
    mobilePriority: 'medium',
    visualDensity: 'balanced',
    allowedSources: commonSources,
    aiSelection: input.aiSelection || {
        canSelect: true,
        selectionGuidance: input.selectionGuidance || [],
        antiPatterns: input.antiPatterns || [],
        confidenceThreshold: input.confidenceThreshold ?? 0.75,
    },
    dataAccess: input.dataAccess || access(['businessProfile', 'brandProfile']),
    ...input,
});

export const componentRegistry: ComponentRegistryEntry[] = [
    entry({
        id: 'header',
        label: 'Header',
        description: 'Global navigation and brand entry point for a generated website or storefront.',
        family: 'global_layout',
        compatibleBuilders: ['website', 'storefront'],
        pageIntents: ['website_home', 'ecommerce_home', 'storefront_home', 'service_landing', 'ai_saas_landing'],
        conversionRoles: ['navigation'],
        recommendedPosition: 'top',
        mobilePriority: 'critical',
        renderTargets: { websiteSection: 'header', storefrontSectionType: 'header' },
        selectionGuidance: ['Use when the generated surface needs first-viewport navigation or brand identity.'],
    }),
    entry({
        id: 'hero',
        label: 'Hero',
        description: 'Primary first-viewport message with CTA, proof, and optional media.',
        family: 'website_content',
        compatibleIndustries: ['all', 'premium_retail', 'electric_bikes', 'restaurant', 'real_estate', 'ai_saas', 'services', 'portfolio'],
        pageIntents: ['website_home', 'service_landing', 'ecommerce_home', 'restaurant_home', 'appointment_landing', 'real_estate_home', 'portfolio_home', 'gallery_home', 'ai_saas_landing', 'lead_capture'],
        conversionRoles: ['awareness', 'lead_capture', 'sales'],
        recommendedPosition: 'top',
        mobilePriority: 'critical',
        renderTargets: { websiteSection: 'hero' },
        selectionGuidance: ['Choose a hero variant from anatomy based on page intent; do not default to centeredMinimal for premium, retail, restaurant, or gallery pages.'],
        antiPatterns: ['Do not use a generic centered hero when the business is product-led, editorial, restaurant, real estate, or premium retail.'],
    }),
    entry({
        id: 'about',
        label: 'About',
        description: 'Business story, positioning, founder narrative, or editorial statement.',
        family: 'website_content',
        implementationStatus: 'metadata_only',
        visualSupportNotes: 'Maps to the existing features section until a dedicated about/image-text renderer consumes anatomy variants.',
        compatibleIndustries: ['all', 'services', 'local_business', 'restaurant', 'portfolio', 'real_estate'],
        pageIntents: ['website_home', 'service_landing', 'local_business_home', 'restaurant_home', 'portfolio_home'],
        conversionRoles: ['education', 'trust'],
        renderTargets: { websiteSection: 'features' },
        selectionGuidance: ['Use when the brief contains differentiated story, craft, founder context, or local trust.'],
    }),
    entry({
        id: 'services',
        label: 'Services',
        description: 'Service list, packages, categories, or offer breakdown.',
        family: 'website_content',
        compatibleIndustries: ['all', 'services', 'local_business', 'real_estate', 'restaurant', 'fitness'],
        pageIntents: ['service_landing', 'local_business_home', 'appointment_landing', 'restaurant_home', 'real_estate_home'],
        conversionRoles: ['education', 'lead_capture'],
        optionalModules: ['services'],
        dataRequirements: [data('servicesCount', 'Service list', 'businessBlueprint.businessProfile.services', 1, false)],
        renderTargets: { websiteSection: 'services' },
        selectionGuidance: ['Prefer when concrete services, appointments, packages, repairs, consultations, or offerings exist.'],
    }),
    entry({
        id: 'features',
        label: 'Features',
        description: 'Feature/value proposition block for software, products, services, or process benefits.',
        family: 'website_content',
        compatibleIndustries: ['all', 'ai_saas', 'digital_products', 'services', 'ecommerce'],
        pageIntents: ['website_home', 'service_landing', 'ai_saas_landing', 'ecommerce_home'],
        conversionRoles: ['education'],
        renderTargets: { websiteSection: 'features' },
    }),
    entry({
        id: 'process',
        label: 'Process',
        description: 'Sequential how-it-works, service flow, onboarding, or buying process.',
        family: 'website_content',
        compatibleIndustries: ['all', 'services', 'ai_saas', 'local_business', 'real_estate'],
        pageIntents: ['service_landing', 'ai_saas_landing', 'local_business_home', 'appointment_landing'],
        conversionRoles: ['education', 'lead_capture'],
        renderTargets: { websiteSection: 'howItWorks' },
    }),
    entry({
        id: 'stats',
        label: 'Stats',
        description: 'Metric proof strip for traction, outcomes, reach, inventory, or trust.',
        family: 'website_content',
        implementationStatus: 'metadata_only',
        visualSupportNotes: 'Uses metadata for future stats rendering; current website renderer does not consume stats anatomy variants directly.',
        compatibleIndustries: ['all', 'ai_saas', 'services', 'real_estate', 'ecommerce'],
        pageIntents: ['website_home', 'service_landing', 'ai_saas_landing', 'real_estate_home'],
        conversionRoles: ['trust'],
        renderTargets: { websiteSection: 'features' },
        selectionGuidance: ['Use only for metrics that can be framed as draft or sourced; avoid fake customer counts and revenue claims.'],
        antiPatterns: ['Do not invent revenue, customer count, review count, sales volume, or inventory statistics.'],
    }),
    entry({
        id: 'testimonials',
        label: 'Testimonials',
        description: 'Social proof through quotes, proof notes, logos, or review-ready placeholders.',
        family: 'website_content',
        compatibleIndustries: ['all', 'services', 'local_business', 'ai_saas', 'restaurant', 'real_estate'],
        pageIntents: ['website_home', 'service_landing', 'local_business_home', 'ai_saas_landing', 'restaurant_home', 'real_estate_home'],
        conversionRoles: ['trust'],
        dataRequirements: [data('testimonialsCount', 'Testimonials or reviews', 'businessBlueprint.reviewSignals', 1, false, true)],
        fallbackComponentId: 'trustBadges',
        renderTargets: { websiteSection: 'testimonials' },
        selectionGuidance: ['Use real testimonials when available; otherwise use trustBadges or proof language marked as draft/needsReview.'],
        antiPatterns: ['Do not generate fake customer names, fake star ratings, or fake reviews as real proof.'],
    }),
    entry({
        id: 'faq',
        label: 'FAQ',
        description: 'Question-and-answer section for objections, policies, booking, services, or ecommerce readiness.',
        family: 'website_content',
        pageIntents: ['website_home', 'service_landing', 'ecommerce_home', 'restaurant_home', 'appointment_landing', 'real_estate_home', 'ai_saas_landing'],
        conversionRoles: ['education', 'compliance'],
        recommendedPosition: 'late',
        mobilePriority: 'medium',
        renderTargets: { websiteSection: 'faq' },
    }),
    entry({
        id: 'pricing',
        label: 'Pricing',
        description: 'Pricing, plans, packages, deposits, or service tiers.',
        family: 'website_content',
        visualSupportNotes: 'Renderer supports dark-saas-cards, featured-plan, voice-credit-columns, dark-plan-cards, finance-comparison, subscription-shop, bi-panels, grouped-plan-grid, workflow-rows, and addon-cards pricingVariant values.',
        compatibleIndustries: ['ai_saas', 'services', 'digital_products', 'fitness'],
        pageIntents: ['ai_saas_landing', 'service_landing', 'appointment_landing'],
        conversionRoles: ['sales', 'lead_capture'],
        optionalModules: ['subscription', 'services'],
        renderTargets: { websiteSection: 'pricing' },
        antiPatterns: ['Do not invent live prices unless the merchant provided them.'],
    }),
    entry({
        id: 'gallery',
        label: 'Gallery',
        description: 'Image-led gallery for portfolio work, spaces, dishes, products, or properties.',
        family: 'website_content',
        compatibleIndustries: ['portfolio', 'gallery', 'restaurant', 'real_estate', 'fitness', 'fashion', 'beauty'],
        pageIntents: ['portfolio_home', 'gallery_home', 'restaurant_home', 'real_estate_home'],
        conversionRoles: ['trust', 'education'],
        dataRequirements: [data('portfolioItemsCount', 'Portfolio or gallery media', 'websitePlan.contentMap.extractedImages', 1, false)],
        renderTargets: { websiteSection: 'portfolio' },
    }),
    entry({
        id: 'showcase',
        label: 'Showcase',
        description: 'Curated visual showcase for image-led work, products, campaigns, media, classes, or editorial collections.',
        family: 'website_content',
        visualSupportNotes: 'Renderer supports featured-device, curated-row, editorial-stack, vertical-strips, dark-carousel, minimal-index, case-grid-dark, and recent-work showcaseVariant values.',
        compatibleIndustries: ['all', 'portfolio', 'gallery', 'agency', 'creative', 'ecommerce', 'restaurant', 'fashion', 'beauty', 'architecture', 'education', 'media', 'ai_saas'],
        pageIntents: ['website_home', 'portfolio_home', 'gallery_home', 'ecommerce_home', 'restaurant_home', 'ai_saas_landing', 'service_landing'],
        conversionRoles: ['trust', 'education', 'product_discovery'],
        dataRequirements: [data('showcaseItemsCount', 'Curated showcase media', 'websitePlan.contentMap.extractedImages', 3, false)],
        minDataRequired: { showcaseItemsCount: 3 },
        recommendedPosition: 'middle',
        mobilePriority: 'high',
        visualDensity: 'rich',
        renderTargets: { websiteSection: 'showcase' },
        selectionGuidance: [
            'Use when the brief asks for a visual index, case-study wall, product/story showcase, media cards, classes, campaigns, or proof that should feel more curated than a standard portfolio.',
            'Prefer over gallery when each image needs title, category, meta, or CTA context.',
        ],
    }),
    entry({
        id: 'imageWithText',
        label: 'Image With Text',
        description: 'Alternating editorial image and copy section for story, value, or proof.',
        family: 'website_content',
        implementationStatus: 'metadata_only',
        visualSupportNotes: 'Maps to features metadata until a dedicated image-with-text renderer is wired.',
        compatibleIndustries: ['all', 'premium_retail', 'restaurant', 'portfolio', 'services'],
        pageIntents: ['website_home', 'ecommerce_home', 'restaurant_home', 'portfolio_home', 'service_landing'],
        conversionRoles: ['education', 'trust'],
        renderTargets: { websiteSection: 'features' },
    }),
    entry({
        id: 'leadForm',
        label: 'Lead Form',
        description: 'Lead capture form for inquiries, quotes, consultations, or waitlists.',
        family: 'lead_block',
        compatibleIndustries: ['all', 'services', 'local_business', 'real_estate', 'ai_saas', 'restaurant'],
        pageIntents: ['lead_capture', 'service_landing', 'appointment_landing', 'real_estate_home', 'local_business_home'],
        conversionRoles: ['lead_capture'],
        requiredModules: ['leadGeneration'],
        recommendedPosition: 'late',
        mobilePriority: 'high',
        renderTargets: { websiteSection: 'leads' },
    }),
    entry({
        id: 'appointmentCTA',
        label: 'Appointment CTA',
        description: 'Booking or appointment-oriented conversion block.',
        family: 'appointment_block',
        implementationStatus: 'rendered',
        visualSupportNotes: 'Renders a public booking form backed by canonical appointment availability and widget API booking writes.',
        compatibleIndustries: ['services', 'local_business', 'fitness', 'beauty', 'restaurant', 'electric_bikes'],
        pageIntents: ['appointment_landing', 'service_landing', 'local_business_home', 'ecommerce_home'],
        conversionRoles: ['booking', 'lead_capture'],
        requiredModules: ['booking'],
        optionalModules: ['appointments'],
        fallbackComponentId: 'leadForm',
        renderTargets: { websiteSection: 'appointmentBooking' },
        selectionGuidance: ['Use for test rides, consultations, repairs, classes, reservations, or service calls when public booking should create canonical appointment requests. Fall back to leadForm when appointment readiness is missing.'],
    }),
    entry({
        id: 'publicBookingForm',
        label: 'Public Booking Form',
        description: 'Public availability picker and appointment request form backed by the canonical Appointments Engine.',
        family: 'appointment_block',
        implementationStatus: 'rendered',
        visualSupportNotes: 'Fetches public availability from the widget API and creates canonical appointment requests with linked lead metadata.',
        compatibleIndustries: ['services', 'local_business', 'fitness', 'beauty', 'restaurant', 'electric_bikes'],
        pageIntents: ['appointment_landing', 'service_landing', 'local_business_home'],
        conversionRoles: ['booking', 'lead_capture'],
        requiredModules: ['booking'],
        optionalModules: ['appointments'],
        fallbackComponentId: 'leadForm',
        renderTargets: { websiteSection: 'appointmentBooking' },
        selectionGuidance: ['Use when a page needs an actual public booking form with available time slots and canonical appointment creation.'],
    }),
    entry({
        id: 'contact',
        label: 'Contact',
        description: 'Contact, location, business hours, and map-ready section.',
        family: 'lead_block',
        compatibleIndustries: ['all', 'local_business', 'restaurant', 'services', 'real_estate'],
        pageIntents: ['local_business_home', 'restaurant_home', 'service_landing', 'real_estate_home', 'lead_capture'],
        conversionRoles: ['lead_capture', 'trust'],
        renderTargets: { websiteSection: 'map' },
    }),
    entry({
        id: 'newsletter',
        label: 'Newsletter',
        description: 'Email capture block for updates, launches, content marketing, or promotions.',
        family: 'lead_block',
        compatibleIndustries: ['all', 'ai_saas', 'ecommerce', 'restaurant', 'portfolio'],
        pageIntents: ['website_home', 'ecommerce_home', 'blog_home', 'portfolio_home', 'ai_saas_landing'],
        conversionRoles: ['retention', 'lead_capture'],
        renderTargets: { websiteSection: 'newsletter' },
    }),
    entry({
        id: 'bioProfile',
        label: 'Bio Profile',
        description: 'Bio Page profile header with avatar, handle, category, bio, and primary CTA.',
        family: 'bio_page_block',
        compatibleBuilders: ['bio-page'],
        compatibleIndustries: ['all', 'creator', 'portfolio', 'ecommerce', 'services', 'restaurant', 'real_estate'],
        pageIntents: ['bio_page'],
        conversionRoles: ['awareness', 'navigation'],
        recommendedPosition: 'top',
        mobilePriority: 'critical',
        allowedSources: bioPageSources,
        dataAccess: access(['bioPageBlueprint.profile'], 'bio-page-engine', 'bio-page-engine'),
        selectionGuidance: ['Use as the first block of every Bio Page. Never invent follower counts, verification, or social proof.'],
        antiPatterns: ['Do not fabricate follower counts, badges, testimonials, reviews, or external identity claims.'],
    }),
    entry({
        id: 'bioLinks',
        label: 'Bio Links',
        description: 'Prioritized link cards for public Bio Pages with click tracking and draft-safe AI links.',
        family: 'bio_page_block',
        compatibleBuilders: ['bio-page'],
        compatibleIndustries: ['all'],
        pageIntents: ['bio_page'],
        conversionRoles: ['navigation', 'lead_capture', 'sales'],
        recommendedPosition: 'early',
        mobilePriority: 'critical',
        allowedSources: bioPageSources,
        dataRequirements: [data('linksCount', 'Visible Bio Page links', 'bioPageBlueprint.links', 1, false)],
        dataAccess: access(['bioPageBlueprint.links'], 'bio-page-engine', 'bio-page-engine'),
        selectionGuidance: ['Use for merchant/user-provided links and internal Quimera module links. AI-generated external links must stay needs_review until confirmed.'],
        antiPatterns: ['Do not generate unsafe javascript URLs or publish AI-invented external destinations.'],
    }),
    entry({
        id: 'bioSocialLinks',
        label: 'Bio Social Links',
        description: 'Compact social icon row backed by provided social URLs.',
        family: 'bio_page_block',
        compatibleBuilders: ['bio-page'],
        compatibleIndustries: ['all', 'creator', 'portfolio'],
        pageIntents: ['bio_page'],
        conversionRoles: ['navigation', 'share'],
        recommendedPosition: 'early',
        mobilePriority: 'high',
        allowedSources: bioPageSources,
        dataAccess: access(['bioPageBlueprint.socialLinks'], 'bio-page-engine', 'bio-page-engine'),
        selectionGuidance: ['Use only when social URLs are provided or imported.'],
    }),
    entry({
        id: 'bioFeaturedBanner',
        label: 'Bio Featured Banner',
        description: 'Promotional Bio Page banner for one reviewed offer, launch, announcement, or internal CTA.',
        family: 'bio_page_block',
        compatibleBuilders: ['bio-page'],
        compatibleIndustries: ['all', 'creator', 'ecommerce', 'restaurant', 'services', 'fitness', 'beauty'],
        pageIntents: ['bio_page'],
        conversionRoles: ['awareness', 'lead_capture', 'sales'],
        recommendedPosition: 'early',
        mobilePriority: 'high',
        allowedSources: bioPageSources,
        dataAccess: access(['bioPageBlueprint.blocks.featured_banner'], 'bio-page-engine', 'bio-page-engine'),
        selectionGuidance: ['Use for one high-priority campaign or offer that the user supplied or can review before publishing.'],
        antiPatterns: ['Do not invent discount claims, launch dates, guarantees, scarcity, or external URLs.'],
    }),
    entry({
        id: 'bioFeaturedMedia',
        label: 'Bio Featured Media',
        description: 'Single featured image, video, or safe media asset from Media AI or project files.',
        family: 'bio_page_block',
        compatibleBuilders: ['bio-page'],
        compatibleIndustries: ['creator', 'portfolio', 'restaurant', 'fitness', 'beauty', 'real_estate'],
        pageIntents: ['bio_page'],
        conversionRoles: ['trust', 'education'],
        recommendedPosition: 'middle',
        mobilePriority: 'medium',
        allowedSources: bioPageSources,
        dataAccess: access(['bioPageBlueprint.blocks.featured_media', 'mediaBlueprint'], 'bio-page-engine', 'bio-page-engine'),
        selectionGuidance: ['Use only when a safe media URL or project asset is available; otherwise leave needs_review or show setup readiness.'],
        antiPatterns: ['Do not render unsafe embeds, broken media URLs, or unrelated stock-like imagery.'],
    }),
    entry({
        id: 'bioShop',
        label: 'Bio Shop',
        description: 'Creator storefront block that displays active Ecommerce products and routes to storefront/product pages.',
        family: 'bio_page_block',
        compatibleBuilders: ['bio-page'],
        compatibleIndustries: ['ecommerce', 'creator', 'restaurant', 'services', 'fitness', 'beauty'],
        pageIntents: ['bio_page'],
        conversionRoles: ['sales', 'product_discovery'],
        requiredModules: ['ecommerce'],
        allowedSources: commerceSources,
        implementationStatus: 'rendered',
        dataRequirements: [data('productsCount', 'Active Ecommerce products', 'ecommerceEngine.store_products', 1, true, true)],
        dataAccess: access(['products', 'prices', 'storefront_routes'], 'ecommerce-engine', 'bio-page-engine'),
        selectionGuidance: ['Render only active/published Ecommerce products. Show setup readiness in editor when no real products exist.'],
        antiPatterns: ['Do not show draft products, fake prices, fake inventory, or fake reviews publicly.'],
    }),
    entry({
        id: 'bioProductCollection',
        label: 'Bio Product Collection',
        description: 'Bio Page collection block that filters real Ecommerce products by selected categories or collections.',
        family: 'bio_page_block',
        compatibleBuilders: ['bio-page'],
        compatibleIndustries: ['ecommerce', 'creator', 'restaurant', 'services', 'fitness', 'beauty'],
        pageIntents: ['bio_page'],
        conversionRoles: ['sales', 'catalog_discovery', 'product_discovery'],
        requiredModules: ['ecommerce'],
        allowedSources: commerceSources,
        implementationStatus: 'rendered',
        dataRequirements: [data('categoriesCount', 'Active Ecommerce categories or collections', 'ecommerceEngine.store_categories', 1, true, true)],
        dataAccess: access(['products', 'categories', 'storefront_routes'], 'ecommerce-engine', 'bio-page-engine'),
        selectionGuidance: ['Use for curated product categories. Public rendering must filter to active/published products only.'],
        antiPatterns: ['Do not create fake collections, fake prices, draft products, or empty public collection promises.'],
    }),
    entry({
        id: 'bioBooking',
        label: 'Bio Booking',
        description: 'Booking CTA block backed by Appointments readiness and public booking routes.',
        family: 'bio_page_block',
        compatibleBuilders: ['bio-page'],
        compatibleIndustries: ['services', 'fitness', 'wellness', 'beauty', 'consulting', 'restaurant', 'real_estate'],
        pageIntents: ['bio_page'],
        conversionRoles: ['booking', 'lead_capture'],
        requiredModules: ['appointments'],
        allowedSources: bioPageSources,
        dataAccess: access(['appointmentsBlueprint.services', 'project_appointments'], 'bio-page-engine', 'bio-page-engine'),
        selectionGuidance: ['Use when Appointments is enabled or the editor can show readiness. Public block must not imply configured availability unless it exists.'],
        antiPatterns: ['Do not invent appointment availability or double-booking-safe slots.'],
    }),
    entry({
        id: 'bioLeadCapture',
        label: 'Bio Lead Capture',
        description: 'Bio Page lead form that writes CRM leads with bio_page source and tags.',
        family: 'bio_page_block',
        compatibleBuilders: ['bio-page'],
        compatibleIndustries: ['all'],
        pageIntents: ['bio_page', 'lead_capture'],
        conversionRoles: ['lead_capture'],
        requiredModules: ['leadGeneration'],
        allowedSources: bioPageSources,
        dataAccess: access(['bioPageBlueprint.leadCapture', 'crm.leads'], 'bio-page-engine', 'bio-page-engine'),
        selectionGuidance: ['Use for inquiries, quotes, waitlists, and high-intent Bio Page traffic.'],
    }),
    entry({
        id: 'bioEmailSubscribe',
        label: 'Bio Email Subscribe',
        description: 'Consent-first email subscribe block connected to Email Marketing audiences.',
        family: 'bio_page_block',
        compatibleBuilders: ['bio-page'],
        compatibleIndustries: ['all', 'creator', 'ecommerce', 'portfolio'],
        pageIntents: ['bio_page'],
        conversionRoles: ['subscribe', 'retention', 'lead_capture'],
        requiredModules: ['contentMarketing'],
        allowedSources: bioPageSources,
        dataAccess: access(['bioPageBlueprint.emailSubscribe', 'emailMarketingBlueprint.audiences'], 'bio-page-engine', 'bio-page-engine'),
        selectionGuidance: ['Require consent text when configured. Email Marketing owns audience membership and suppression rules.'],
        antiPatterns: ['Do not subscribe users without consent or expose audience lists publicly.'],
    }),
    entry({
        id: 'bioMediaGrid',
        label: 'Bio Media Grid',
        description: 'Media grid for images, video placeholders, and Media AI assets.',
        family: 'bio_page_block',
        compatibleBuilders: ['bio-page'],
        implementationStatus: 'rendered',
        visualSupportNotes: 'The Bio renderer supports safe image/video cards from provided project media. Third-party embed importing remains future work.',
        compatibleIndustries: ['creator', 'portfolio', 'restaurant', 'fitness', 'beauty'],
        pageIntents: ['bio_page'],
        conversionRoles: ['trust', 'education'],
        allowedSources: bioPageSources,
        dataAccess: access(['bioPageBlueprint.blocks.media_grid', 'mediaBlueprint'], 'bio-page-engine', 'bio-page-engine'),
    }),
    entry({
        id: 'bioPortfolio',
        label: 'Bio Portfolio',
        description: 'Portfolio or project grid for visual work and case-study links.',
        family: 'bio_page_block',
        compatibleBuilders: ['bio-page'],
        implementationStatus: 'rendered',
        visualSupportNotes: 'The Bio renderer supports reviewed static portfolio cards from block data. Automatic project import remains future work.',
        compatibleIndustries: ['portfolio', 'creator', 'gallery', 'real_estate'],
        pageIntents: ['bio_page', 'portfolio_home'],
        conversionRoles: ['trust', 'education', 'lead_capture'],
        allowedSources: bioPageSources,
        dataAccess: access(['bioPageBlueprint.blocks.portfolio_grid', 'mediaBlueprint'], 'bio-page-engine', 'bio-page-engine'),
        antiPatterns: ['Do not invent client work, awards, or fake project outcomes.'],
    }),
    entry({
        id: 'bioTestimonials',
        label: 'Bio Testimonials',
        description: 'Manual proof block for reviewed testimonials or short social proof quotes.',
        family: 'bio_page_block',
        compatibleBuilders: ['bio-page'],
        compatibleIndustries: ['all', 'creator', 'portfolio', 'services', 'ecommerce', 'fitness', 'beauty'],
        pageIntents: ['bio_page'],
        conversionRoles: ['trust'],
        implementationStatus: 'rendered',
        allowedSources: bioPageSources,
        dataAccess: access(['bioPageBlueprint.blocks.testimonials'], 'bio-page-engine', 'bio-page-engine'),
        selectionGuidance: ['Use only for user-supplied or imported testimonials that remain needs_review until manually verified.'],
        antiPatterns: ['Do not fabricate testimonials, ratings, reviews, customer names, or proof claims.'],
    }),
    entry({
        id: 'bioFaq',
        label: 'Bio FAQ',
        description: 'Compact Bio Page FAQ block for high-intent questions and conversion objections.',
        family: 'bio_page_block',
        compatibleBuilders: ['bio-page'],
        compatibleIndustries: ['all'],
        pageIntents: ['bio_page'],
        conversionRoles: ['education', 'trust'],
        implementationStatus: 'rendered',
        allowedSources: bioPageSources,
        dataAccess: access(['bioPageBlueprint.blocks.faq'], 'bio-page-engine', 'bio-page-engine'),
        selectionGuidance: ['Use for factual questions derived from the business brief, services, products, booking, or policies.'],
        antiPatterns: ['Do not invent legal, medical, pricing, refund, availability, or guarantee claims.'],
    }),
    entry({
        id: 'bioContact',
        label: 'Bio Contact',
        description: 'Direct contact block for reviewed email, phone, WhatsApp, website, and address CTAs.',
        family: 'bio_page_block',
        compatibleBuilders: ['bio-page'],
        compatibleIndustries: ['all', 'local_business', 'restaurant', 'services', 'real_estate'],
        pageIntents: ['bio_page', 'lead_capture'],
        conversionRoles: ['lead_capture', 'navigation'],
        implementationStatus: 'rendered',
        allowedSources: bioPageSources,
        dataAccess: access(['bioPageBlueprint.blocks.contact', 'businessProfile.contactInfo'], 'bio-page-engine', 'bio-page-engine'),
        selectionGuidance: ['Use only contact values supplied by the user, import, project settings, or CRM-safe business profile.'],
        antiPatterns: ['Do not invent email addresses, phone numbers, WhatsApp numbers, locations, or map links.'],
    }),
    entry({
        id: 'bioChatCTA',
        label: 'Bio Chat CTA',
        description: 'Inline ChatCore CTA and floating chat context for a public Bio Page.',
        family: 'bio_page_block',
        compatibleBuilders: ['bio-page'],
        compatibleIndustries: ['all'],
        pageIntents: ['bio_page'],
        conversionRoles: ['chat', 'lead_capture'],
        optionalModules: ['leadGeneration', 'ecommerce', 'appointments'],
        allowedSources: bioPageSources,
        dataAccess: access(['bioPageBlueprint.chatbot', 'chatbotBlueprint'], 'bio-page-engine', 'bio-page-engine'),
        selectionGuidance: ['Use when ChatCore is enabled. Pass visible Bio Page blocks as context and tag captured leads as bio_page_chat.'],
    }),
    entry({
        id: 'featuredProducts',
        label: 'Featured Products',
        description: 'Website ecommerce block that presents products sourced from Ecommerce Engine.',
        family: 'website_ecommerce_block',
        compatibleIndustries: ['ecommerce', 'premium_retail', 'electric_bikes', 'fashion', 'beauty', 'fitness', 'marketplace', 'restaurant'],
        pageIntents: ['ecommerce_home', 'storefront_home'],
        conversionRoles: ['sales', 'product_discovery'],
        requiredModules: ['ecommerce'],
        dataRequirements: [data('productsCount', 'Products or reviewable product drafts', 'ecommerceBlueprint.starterProducts', 1)],
        minDataRequired: { productsCount: 1 },
        allowedSources: commerceSources,
        requiredFeature: 'ecommerceEnabled',
        fallbackComponentId: 'shopCTA',
        dataAccess: access(['products', 'prices', 'categories', 'storefront_routes'], 'ecommerce-engine'),
        renderTargets: { websiteSection: 'featuredProducts', websiteEcommerceBlock: 'featuredProducts', storefrontSectionType: 'featuredProducts' },
        selectionGuidance: ['Use only when Ecommerce Engine has real products or reviewable starter product drafts.'],
        antiPatterns: ['Do not show products, prices, inventory, discounts, or ratings as real unless they came from Ecommerce Engine or merchant input.'],
    }),
    entry({
        id: 'productCarousel',
        label: 'Product Carousel',
        description: 'Scrollable product discovery block for enough products to justify a carousel.',
        family: 'website_ecommerce_block',
        implementationStatus: 'metadata_only',
        visualSupportNotes: 'Creates website ecommerce block metadata with carousel intent; existing visual section is featuredProducts.',
        compatibleIndustries: ['ecommerce', 'premium_retail', 'fashion', 'beauty', 'fitness', 'marketplace'],
        pageIntents: ['ecommerce_home', 'storefront_home'],
        conversionRoles: ['sales', 'product_discovery'],
        requiredModules: ['ecommerce'],
        dataRequirements: [data('productsCount', 'Products or reviewable product drafts', 'ecommerceBlueprint.starterProducts', 4)],
        minDataRequired: { productsCount: 4 },
        allowedSources: commerceSources,
        requiredFeature: 'ecommerceEnabled',
        fallbackComponentId: 'featuredProducts',
        dataAccess: access(['products', 'prices', 'storefront_routes'], 'ecommerce-engine'),
        renderTargets: { websiteSection: 'featuredProducts', websiteEcommerceBlock: 'productCarousel', storefrontSectionType: 'featuredProducts' },
    }),
    entry({
        id: 'categoryShowcase',
        label: 'Category Showcase',
        description: 'Website ecommerce block for product categories or collections.',
        family: 'website_ecommerce_block',
        compatibleIndustries: ['ecommerce', 'premium_retail', 'electric_bikes', 'marketplace', 'restaurant'],
        pageIntents: ['ecommerce_home', 'storefront_home', 'product_collection'],
        conversionRoles: ['catalog_discovery', 'sales'],
        requiredModules: ['ecommerce'],
        dataRequirements: [data('categoriesCount', 'Categories or collections', 'ecommerceBlueprint.productCategories', 1)],
        minDataRequired: { categoriesCount: 1 },
        allowedSources: commerceSources,
        requiredFeature: 'ecommerceEnabled',
        fallbackComponentId: 'shopCTA',
        dataAccess: access(['categories', 'collections', 'storefront_routes'], 'ecommerce-engine'),
        renderTargets: { websiteSection: 'categoryGrid', websiteEcommerceBlock: 'categoryShowcase', storefrontSectionType: 'categoryGrid' },
    }),
    entry({
        id: 'shopCTA',
        label: 'Shop CTA',
        description: 'Fallback website CTA that routes into storefront without implying catalog readiness.',
        family: 'website_ecommerce_block',
        compatibleIndustries: ['ecommerce', 'premium_retail', 'marketplace', 'restaurant', 'services'],
        pageIntents: ['ecommerce_home', 'storefront_home', 'service_landing'],
        conversionRoles: ['sales', 'navigation'],
        optionalModules: ['ecommerce'],
        allowedSources: commerceSources,
        dataAccess: access(['storefront_routes'], 'ecommerce-engine'),
        renderTargets: { websiteSection: 'cta', websiteEcommerceBlock: 'shopCTA', storefrontSectionType: 'shopCTA' },
        selectionGuidance: ['Use as fallback when ecommerce is enabled but catalog data is incomplete.'],
    }),
    entry({
        id: 'saleCountdown',
        label: 'Sale Countdown',
        description: 'Promotion countdown block tied to a real merchant-approved promotion.',
        family: 'website_ecommerce_block',
        compatibleIndustries: ['ecommerce', 'retail', 'fashion', 'beauty', 'fitness'],
        pageIntents: ['ecommerce_home', 'storefront_home'],
        conversionRoles: ['sales'],
        requiredModules: ['ecommerce'],
        dataRequirements: [data('hasMerchantApprovedPromotion', 'Merchant-approved promotion', 'ecommerceBlueprint.discounts', 1, true, true)],
        allowedSources: commerceSources,
        requiredFeature: 'ecommerceEnabled',
        fallbackComponentId: 'shopCTA',
        dataAccess: access(['discounts', 'storefront_routes'], 'ecommerce-engine'),
        renderTargets: { websiteSection: 'saleCountdown', websiteEcommerceBlock: 'promoBanner', storefrontSectionType: 'saleCountdown' },
        antiPatterns: ['Do not create active discounts, false urgency, or countdown timers without merchant approval.'],
    }),
    entry({
        id: 'trustBadges',
        label: 'Trust Badges',
        description: 'Compact trust cues for shipping, payment, local service, guarantees, certifications, or safety.',
        family: 'website_content',
        compatibleIndustries: ['all', 'ecommerce', 'services', 'local_business', 'restaurant', 'real_estate'],
        pageIntents: ['website_home', 'service_landing', 'ecommerce_home', 'restaurant_home', 'real_estate_home', 'local_business_home'],
        conversionRoles: ['trust'],
        renderTargets: { websiteSection: 'trustBadges', storefrontSectionType: 'trustBadges' },
        antiPatterns: ['Do not imply certifications, guarantees, reviews, payment readiness, or shipping policies that were not provided.'],
    }),
    entry({
        id: 'productHero',
        label: 'Product Hero',
        description: 'Product detail or product-led hero for storefront/product pages.',
        family: 'product_page_section',
        compatibleBuilders: ['storefront', 'ecommerce'],
        compatibleIndustries: ['ecommerce', 'premium_retail', 'electric_bikes', 'fashion', 'fitness', 'beauty'],
        pageIntents: ['product_detail', 'storefront_home', 'ecommerce_home'],
        conversionRoles: ['sales', 'product_discovery'],
        requiredModules: ['ecommerce'],
        allowedSources: commerceSources,
        dataAccess: access(['products', 'prices', 'media'], 'ecommerce-engine', 'storefront-builder'),
        renderTargets: { storefrontSectionType: 'productHero' },
    }),
    entry({
        id: 'collectionBanner',
        label: 'Collection Banner',
        description: 'Collection/category header for storefront collection pages.',
        family: 'collection_section',
        compatibleBuilders: ['storefront', 'ecommerce'],
        compatibleIndustries: ['ecommerce', 'marketplace', 'premium_retail', 'fashion', 'fitness'],
        pageIntents: ['product_collection', 'storefront_home'],
        conversionRoles: ['catalog_discovery'],
        requiredModules: ['ecommerce'],
        allowedSources: commerceSources,
        dataAccess: access(['collections', 'categories', 'storefront_routes'], 'ecommerce-engine', 'storefront-builder'),
        renderTargets: { storefrontSectionType: 'collectionBanner' },
    }),
    entry({
        id: 'restaurantMenu',
        label: 'Restaurant Menu',
        description: 'Restaurant menu, catering, gift card, or featured dishes section.',
        family: 'restaurant_block',
        compatibleIndustries: ['restaurant', 'food', 'cafe', 'bakery'],
        pageIntents: ['restaurant_home'],
        conversionRoles: ['education', 'sales'],
        requiredModules: ['restaurant'],
        dataRequirements: [data('menuItemsCount', 'Restaurant menu drafts', 'restaurantBlueprint.menuDraft.items', 1, false)],
        allowedSources: ['businessBlueprint', 'restaurantBlueprint', 'restaurantEngine'],
        dataAccess: access(['restaurantBlueprint.menuDraft', 'restaurantMenuItems'], 'restaurant-engine', 'website-builder'),
        renderTargets: { websiteSection: 'menu' },
    }),
    entry({
        id: 'restaurantReservation',
        label: 'Restaurant Reservation',
        description: 'Reservation or catering inquiry block for restaurant businesses.',
        family: 'restaurant_block',
        compatibleIndustries: ['restaurant', 'food'],
        pageIntents: ['restaurant_home', 'appointment_landing'],
        conversionRoles: ['booking', 'lead_capture'],
        requiredModules: ['restaurantReservations'],
        dataRequirements: [data('reservationSettings', 'Reservation draft settings', 'restaurantBlueprint.reservations', 1, false)],
        allowedSources: ['businessBlueprint', 'restaurantBlueprint', 'restaurantEngine'],
        dataAccess: access(['restaurantBlueprint.reservations', 'restaurantReservations'], 'restaurant-engine', 'website-builder'),
        fallbackComponentId: 'leadForm',
        renderTargets: { websiteSection: 'restaurantReservation' },
    }),
    entry({
        id: 'restaurantLocation',
        label: 'Restaurant Location',
        description: 'Location, hours, neighborhood, and contact block for restaurants.',
        family: 'restaurant_block',
        compatibleIndustries: ['restaurant', 'food', 'local_business'],
        pageIntents: ['restaurant_home', 'local_business_home'],
        conversionRoles: ['trust', 'lead_capture'],
        dataRequirements: [data('restaurantProfile', 'Restaurant profile and hours', 'restaurantBlueprint.profile', 1, false)],
        allowedSources: ['businessBlueprint', 'restaurantBlueprint', 'restaurantEngine'],
        dataAccess: access(['restaurantBlueprint.profile', 'restaurantSettings'], 'restaurant-engine', 'website-builder'),
        renderTargets: { websiteSection: 'map' },
    }),
    entry({
        id: 'realEstateListings',
        label: 'Real Estate Listings',
        description: 'Property listings, listing teasers, or draft listing directory entry point.',
        family: 'real_estate_block',
        compatibleIndustries: ['real_estate'],
        pageIntents: ['real_estate_home'],
        conversionRoles: ['lead_capture', 'catalog_discovery'],
        requiredModules: ['realEstate'],
        dataRequirements: [data('listingsCount', 'Published Realty Engine listings or reviewable listing drafts', 'realEstateBlueprint.listingDrafts', 1, false)],
        allowedSources: ['businessBlueprint', 'realEstateBlueprint', 'realtyEngine'],
        dataAccess: access(['realEstateBlueprint.listingDrafts', 'realtyProperties', 'publicRealtyListings'], 'real-estate-engine', 'website-builder'),
        renderTargets: { websiteSection: 'realEstateListings' },
        selectionGuidance: [
            'Use as the only rendered Realty homepage block until propertySearch and neighborhoods have render-ready implementations.',
            'The block reads active public listings from Realty Engine; Website Builder may configure presentation, routes, and CTAs only.',
        ],
        antiPatterns: [
            'Do not store listing rows in Website Builder data.',
            'Do not publish draft or needs-review listings through AI Studio.',
        ],
    }),
    entry({
        id: 'propertySearch',
        label: 'Property Search',
        description: 'Search or filter entry point for real estate visitors.',
        family: 'real_estate_block',
        implementationStatus: 'planned',
        visualSupportNotes: 'Property search is represented as intent metadata; the homepage renderer must not mount propertyDirectory as a search section yet.',
        compatibleIndustries: ['real_estate'],
        pageIntents: ['real_estate_home'],
        conversionRoles: ['lead_capture', 'catalog_discovery'],
        requiredModules: ['realEstate'],
        fallbackComponentId: 'realEstateListings',
        renderTargets: { websiteSection: 'propertyDirectory' },
        aiSelection: {
            canSelect: false,
            selectionGuidance: ['Keep as planning metadata until a dedicated rendered search block is available.'],
            antiPatterns: ['Do not mount propertyDirectory as a homepage search section.'],
            confidenceThreshold: 1,
        },
    }),
    entry({
        id: 'neighborhoods',
        label: 'Neighborhoods',
        description: 'Neighborhood, market, or buyer/seller education section for real estate.',
        family: 'real_estate_block',
        implementationStatus: 'metadata_only',
        visualSupportNotes: 'Maps to features metadata until dedicated neighborhood cards are implemented.',
        compatibleIndustries: ['real_estate'],
        pageIntents: ['real_estate_home'],
        conversionRoles: ['education', 'trust'],
        requiredModules: ['realEstate'],
        fallbackComponentId: 'realEstateListings',
        renderTargets: { websiteSection: 'features' },
        aiSelection: {
            canSelect: false,
            selectionGuidance: ['Keep as planning metadata until dedicated neighborhood cards are implemented.'],
            antiPatterns: ['Do not invent neighborhood or market data as public proof.'],
            confidenceThreshold: 1,
        },
    }),
    entry({
        id: 'footer',
        label: 'Footer',
        description: 'Global footer with navigation, contact, legal, social, newsletter, CTA, landscape, and oversized wordmark treatments.',
        family: 'global_layout',
        compatibleBuilders: ['website', 'storefront'],
        pageIntents: ['website_home', 'service_landing', 'ecommerce_home', 'storefront_home', 'restaurant_home', 'real_estate_home', 'portfolio_home', 'gallery_home', 'ai_saas_landing', 'blog_home', 'lead_capture', 'local_business_home'],
        conversionRoles: ['navigation', 'compliance', 'subscribe', 'lead_capture', 'share'],
        recommendedPosition: 'footer',
        mobilePriority: 'medium',
        selectionGuidance: [
            'Choose a footer layout variant from componentAnatomyRegistry.footer and map it to footer.footerVariant during rendering.',
            'Prefer wordmark-driven variants for strong product brands, press-landscape for regulated/trust-heavy brands, cta-card or grid-newsletter for conversion, and social-directory for community/social products.',
        ],
        antiPatterns: [
            'Do not invent extra footer section IDs; all footer treatments are variants of footer.',
            'Do not put contact details inside linkColumns when contactInfo exists.',
        ],
        renderTargets: { websiteSection: 'footer', storefrontSectionType: 'storeFooter' },
    }),
    entry({
        id: 'storefrontFeaturedProducts',
        label: 'Storefront Featured Products',
        description: 'Storefront-only featured product section controlled by Storefront Builder.',
        family: 'storefront_section',
        compatibleBuilders: ['storefront'],
        compatibleIndustries: ['ecommerce', 'premium_retail', 'marketplace'],
        pageIntents: ['storefront_home'],
        conversionRoles: ['sales', 'product_discovery'],
        requiredModules: ['ecommerce'],
        allowedSources: commerceSources,
        dataAccess: access(['products', 'prices'], 'ecommerce-engine', 'storefront-builder'),
        renderTargets: { storefrontSectionType: 'featuredProducts' },
    }),
    entry({
        id: 'storefrontCategoryGrid',
        label: 'Storefront Category Grid',
        description: 'Storefront-only category section controlled by Storefront Builder.',
        family: 'storefront_section',
        compatibleBuilders: ['storefront'],
        compatibleIndustries: ['ecommerce', 'marketplace'],
        pageIntents: ['storefront_home', 'product_collection'],
        conversionRoles: ['catalog_discovery'],
        requiredModules: ['ecommerce'],
        allowedSources: commerceSources,
        dataAccess: access(['categories', 'collections'], 'ecommerce-engine', 'storefront-builder'),
        renderTargets: { storefrontSectionType: 'categoryGrid' },
    }),
];

export const componentRegistryById: Record<ComponentId, ComponentRegistryEntry> = componentRegistry.reduce((acc, component) => {
    acc[component.id] = component;
    return acc;
}, {} as Record<ComponentId, ComponentRegistryEntry>);

export const isComponentId = (value: unknown): value is ComponentId => (
    typeof value === 'string' && value in componentRegistryById
);

export const getComponentDefinition = (componentId: ComponentId | string): ComponentRegistryEntry | undefined => (
    isComponentId(componentId) ? componentRegistryById[componentId] : undefined
);

export const getComponentsForBuilder = (builder: ComponentBuilder): ComponentRegistryEntry[] => (
    componentRegistry.filter(component => component.compatibleBuilders.includes(builder))
);

export const getComponentsByFamily = (family: ComponentRegistryFamily): ComponentRegistryEntry[] => (
    componentRegistry.filter(component => component.family === family)
);
