import type {
    BusinessCapability,
    ComponentBuilder,
    ComponentDataAccess,
    ComponentDataRequirement,
    ComponentId,
    ComponentImplementationStatus,
    ComponentRegistryEntry,
    ComponentRegistryFamily,
    ConversionRole,
    MobilePriority,
    PageIntent,
    RecommendedPosition,
    VisualDensity,
} from '../types/componentRegistry';

const commonSources = ['userPrompt', 'businessBlueprint', 'websitePlan', 'existingWebsitePlan'];
const commerceSources = ['businessBlueprint', 'ecommerceBlueprint', 'storefrontBlueprint', 'ecommerceEngine'];

const access = (
    reads: string[],
    canonicalSystem: ComponentDataAccess['canonicalSystem'] = 'business-blueprint',
    presentationOwner: ComponentDataAccess['presentationOwner'] = 'website-builder',
): ComponentDataAccess => ({
    reads,
    writes: [],
    canonicalSystem,
    presentationOwner,
});

const data = (
    key: string,
    label: string,
    source: string,
    minCount = 1,
    required = true,
    mustBeMerchantApproved = false,
): ComponentDataRequirement => ({
    key,
    label,
    source,
    minCount,
    required,
    mustBeMerchantApproved,
});

const entry = (input: {
    id: ComponentId;
    label: string;
    description: string;
    family: ComponentRegistryFamily;
    implementationStatus?: ComponentImplementationStatus;
    visualSupportNotes?: string;
    compatibleBuilders?: ComponentBuilder[];
    compatibleIndustries?: string[];
    incompatibleIndustries?: string[];
    pageIntents?: PageIntent[];
    conversionRoles?: ConversionRole[];
    requiredModules?: BusinessCapability[];
    optionalModules?: BusinessCapability[];
    dataRequirements?: ComponentDataRequirement[];
    minDataRequired?: Record<string, number>;
    recommendedPosition?: RecommendedPosition;
    mobilePriority?: MobilePriority;
    visualDensity?: VisualDensity;
    allowedSources?: string[];
    requiredPlan?: string;
    requiredFeature?: string;
    fallbackComponentId?: ComponentId;
    selectionGuidance?: string[];
    antiPatterns?: string[];
    confidenceThreshold?: number;
    dataAccess?: ComponentDataAccess;
    renderTargets?: ComponentRegistryEntry['renderTargets'];
}): ComponentRegistryEntry => ({
    compatibleBuilders: ['website'],
    implementationStatus: 'rendered',
    compatibleIndustries: ['all'],
    incompatibleIndustries: [],
    pageIntents: ['website_home'],
    conversionRoles: ['awareness'],
    requiredModules: [],
    optionalModules: [],
    dataRequirements: [],
    minDataRequired: {},
    recommendedPosition: 'middle',
    mobilePriority: 'medium',
    visualDensity: 'balanced',
    allowedSources: commonSources,
    aiSelection: {
        canSelect: true,
        selectionGuidance: input.selectionGuidance || [],
        antiPatterns: input.antiPatterns || [],
        confidenceThreshold: input.confidenceThreshold ?? 0.75,
    },
    dataAccess: input.dataAccess || access(['businessProfile', 'brandProfile']),
    ...input,
});

export const componentRegistry: ComponentRegistryEntry[] = [
    entry({
        id: 'header',
        label: 'Header',
        description: 'Global navigation and brand entry point for a generated website or storefront.',
        family: 'global_layout',
        compatibleBuilders: ['website', 'storefront'],
        pageIntents: ['website_home', 'ecommerce_home', 'storefront_home', 'service_landing', 'ai_saas_landing'],
        conversionRoles: ['navigation'],
        recommendedPosition: 'top',
        mobilePriority: 'critical',
        renderTargets: { websiteSection: 'header', storefrontSectionType: 'header' },
        selectionGuidance: ['Use when the generated surface needs first-viewport navigation or brand identity.'],
    }),
    entry({
        id: 'hero',
        label: 'Hero',
        description: 'Primary first-viewport message with CTA, proof, and optional media.',
        family: 'website_content',
        compatibleIndustries: ['all', 'premium_retail', 'electric_bikes', 'restaurant', 'real_estate', 'ai_saas', 'services', 'portfolio'],
        pageIntents: ['website_home', 'service_landing', 'ecommerce_home', 'restaurant_home', 'appointment_landing', 'real_estate_home', 'portfolio_home', 'gallery_home', 'ai_saas_landing', 'lead_capture'],
        conversionRoles: ['awareness', 'lead_capture', 'sales'],
        recommendedPosition: 'top',
        mobilePriority: 'critical',
        renderTargets: { websiteSection: 'hero' },
        selectionGuidance: ['Choose a hero variant from anatomy based on page intent; do not default to centeredMinimal for premium, retail, restaurant, or gallery pages.'],
        antiPatterns: ['Do not use a generic centered hero when the business is product-led, editorial, restaurant, real estate, or premium retail.'],
    }),
    entry({
        id: 'about',
        label: 'About',
        description: 'Business story, positioning, founder narrative, or editorial statement.',
        family: 'website_content',
        implementationStatus: 'metadata_only',
        visualSupportNotes: 'Maps to the existing features section until a dedicated about/image-text renderer consumes anatomy variants.',
        compatibleIndustries: ['all', 'services', 'local_business', 'restaurant', 'portfolio', 'real_estate'],
        pageIntents: ['website_home', 'service_landing', 'local_business_home', 'restaurant_home', 'portfolio_home'],
        conversionRoles: ['education', 'trust'],
        renderTargets: { websiteSection: 'features' },
        selectionGuidance: ['Use when the brief contains differentiated story, craft, founder context, or local trust.'],
    }),
    entry({
        id: 'services',
        label: 'Services',
        description: 'Service list, packages, categories, or offer breakdown.',
        family: 'website_content',
        compatibleIndustries: ['all', 'services', 'local_business', 'real_estate', 'restaurant', 'fitness'],
        pageIntents: ['service_landing', 'local_business_home', 'appointment_landing', 'restaurant_home', 'real_estate_home'],
        conversionRoles: ['education', 'lead_capture'],
        optionalModules: ['services'],
        dataRequirements: [data('servicesCount', 'Service list', 'businessBlueprint.businessProfile.services', 1, false)],
        renderTargets: { websiteSection: 'services' },
        selectionGuidance: ['Prefer when concrete services, appointments, packages, repairs, consultations, or offerings exist.'],
    }),
    entry({
        id: 'features',
        label: 'Features',
        description: 'Feature/value proposition block for software, products, services, or process benefits.',
        family: 'website_content',
        compatibleIndustries: ['all', 'ai_saas', 'digital_products', 'services', 'ecommerce'],
        pageIntents: ['website_home', 'service_landing', 'ai_saas_landing', 'ecommerce_home'],
        conversionRoles: ['education'],
        renderTargets: { websiteSection: 'features' },
    }),
    entry({
        id: 'process',
        label: 'Process',
        description: 'Sequential how-it-works, service flow, onboarding, or buying process.',
        family: 'website_content',
        compatibleIndustries: ['all', 'services', 'ai_saas', 'local_business', 'real_estate'],
        pageIntents: ['service_landing', 'ai_saas_landing', 'local_business_home', 'appointment_landing'],
        conversionRoles: ['education', 'lead_capture'],
        renderTargets: { websiteSection: 'howItWorks' },
    }),
    entry({
        id: 'stats',
        label: 'Stats',
        description: 'Metric proof strip for traction, outcomes, reach, inventory, or trust.',
        family: 'website_content',
        implementationStatus: 'metadata_only',
        visualSupportNotes: 'Uses metadata for future stats rendering; current website renderer does not consume stats anatomy variants directly.',
        compatibleIndustries: ['all', 'ai_saas', 'services', 'real_estate', 'ecommerce'],
        pageIntents: ['website_home', 'service_landing', 'ai_saas_landing', 'real_estate_home'],
        conversionRoles: ['trust'],
        renderTargets: { websiteSection: 'features' },
        selectionGuidance: ['Use only for metrics that can be framed as draft or sourced; avoid fake customer counts and revenue claims.'],
        antiPatterns: ['Do not invent revenue, customer count, review count, sales volume, or inventory statistics.'],
    }),
    entry({
        id: 'testimonials',
        label: 'Testimonials',
        description: 'Social proof through quotes, proof notes, logos, or review-ready placeholders.',
        family: 'website_content',
        compatibleIndustries: ['all', 'services', 'local_business', 'ai_saas', 'restaurant', 'real_estate'],
        pageIntents: ['website_home', 'service_landing', 'local_business_home', 'ai_saas_landing', 'restaurant_home', 'real_estate_home'],
        conversionRoles: ['trust'],
        dataRequirements: [data('testimonialsCount', 'Testimonials or reviews', 'businessBlueprint.reviewSignals', 1, false, true)],
        fallbackComponentId: 'trustBadges',
        renderTargets: { websiteSection: 'testimonials' },
        selectionGuidance: ['Use real testimonials when available; otherwise use trustBadges or proof language marked as draft/needsReview.'],
        antiPatterns: ['Do not generate fake customer names, fake star ratings, or fake reviews as real proof.'],
    }),
    entry({
        id: 'faq',
        label: 'FAQ',
        description: 'Question-and-answer section for objections, policies, booking, services, or ecommerce readiness.',
        family: 'website_content',
        pageIntents: ['website_home', 'service_landing', 'ecommerce_home', 'restaurant_home', 'appointment_landing', 'real_estate_home', 'ai_saas_landing'],
        conversionRoles: ['education', 'compliance'],
        recommendedPosition: 'late',
        mobilePriority: 'medium',
        renderTargets: { websiteSection: 'faq' },
    }),
    entry({
        id: 'pricing',
        label: 'Pricing',
        description: 'Pricing, plans, packages, deposits, or service tiers.',
        family: 'website_content',
        compatibleIndustries: ['ai_saas', 'services', 'digital_products', 'fitness'],
        pageIntents: ['ai_saas_landing', 'service_landing', 'appointment_landing'],
        conversionRoles: ['sales', 'lead_capture'],
        optionalModules: ['subscription', 'services'],
        renderTargets: { websiteSection: 'pricing' },
        antiPatterns: ['Do not invent live prices unless the merchant provided them.'],
    }),
    entry({
        id: 'gallery',
        label: 'Gallery',
        description: 'Image-led gallery for portfolio work, spaces, dishes, products, or properties.',
        family: 'website_content',
        compatibleIndustries: ['portfolio', 'gallery', 'restaurant', 'real_estate', 'fitness', 'fashion', 'beauty'],
        pageIntents: ['portfolio_home', 'gallery_home', 'restaurant_home', 'real_estate_home'],
        conversionRoles: ['trust', 'education'],
        dataRequirements: [data('portfolioItemsCount', 'Portfolio or gallery media', 'websitePlan.contentMap.extractedImages', 1, false)],
        renderTargets: { websiteSection: 'portfolio' },
    }),
    entry({
        id: 'imageWithText',
        label: 'Image With Text',
        description: 'Alternating editorial image and copy section for story, value, or proof.',
        family: 'website_content',
        implementationStatus: 'metadata_only',
        visualSupportNotes: 'Maps to features metadata until a dedicated image-with-text renderer is wired.',
        compatibleIndustries: ['all', 'premium_retail', 'restaurant', 'portfolio', 'services'],
        pageIntents: ['website_home', 'ecommerce_home', 'restaurant_home', 'portfolio_home', 'service_landing'],
        conversionRoles: ['education', 'trust'],
        renderTargets: { websiteSection: 'features' },
    }),
    entry({
        id: 'leadForm',
        label: 'Lead Form',
        description: 'Lead capture form for inquiries, quotes, consultations, or waitlists.',
        family: 'lead_block',
        compatibleIndustries: ['all', 'services', 'local_business', 'real_estate', 'ai_saas', 'restaurant'],
        pageIntents: ['lead_capture', 'service_landing', 'appointment_landing', 'real_estate_home', 'local_business_home'],
        conversionRoles: ['lead_capture'],
        requiredModules: ['leadGeneration'],
        recommendedPosition: 'late',
        mobilePriority: 'high',
        renderTargets: { websiteSection: 'leads' },
    }),
    entry({
        id: 'appointmentCTA',
        label: 'Appointment CTA',
        description: 'Booking or appointment-oriented conversion block.',
        family: 'appointment_block',
        implementationStatus: 'metadata_only',
        visualSupportNotes: 'Uses the existing leads section as a safe fallback; appointment-specific visual controls are not fully rendered yet.',
        compatibleIndustries: ['services', 'local_business', 'fitness', 'beauty', 'restaurant', 'electric_bikes'],
        pageIntents: ['appointment_landing', 'service_landing', 'local_business_home', 'ecommerce_home'],
        conversionRoles: ['booking', 'lead_capture'],
        requiredModules: ['booking'],
        optionalModules: ['appointments'],
        fallbackComponentId: 'leadForm',
        renderTargets: { websiteSection: 'leads' },
        selectionGuidance: ['Use for test rides, consultations, repairs, classes, reservations, or service calls. Fall back to leadForm when appointment readiness is missing.'],
    }),
    entry({
        id: 'contact',
        label: 'Contact',
        description: 'Contact, location, business hours, and map-ready section.',
        family: 'lead_block',
        compatibleIndustries: ['all', 'local_business', 'restaurant', 'services', 'real_estate'],
        pageIntents: ['local_business_home', 'restaurant_home', 'service_landing', 'real_estate_home', 'lead_capture'],
        conversionRoles: ['lead_capture', 'trust'],
        renderTargets: { websiteSection: 'map' },
    }),
    entry({
        id: 'newsletter',
        label: 'Newsletter',
        description: 'Email capture block for updates, launches, content marketing, or promotions.',
        family: 'lead_block',
        compatibleIndustries: ['all', 'ai_saas', 'ecommerce', 'restaurant', 'portfolio'],
        pageIntents: ['website_home', 'ecommerce_home', 'blog_home', 'portfolio_home', 'ai_saas_landing'],
        conversionRoles: ['retention', 'lead_capture'],
        renderTargets: { websiteSection: 'newsletter' },
    }),
    entry({
        id: 'featuredProducts',
        label: 'Featured Products',
        description: 'Website ecommerce block that presents products sourced from Ecommerce Engine.',
        family: 'website_ecommerce_block',
        compatibleIndustries: ['ecommerce', 'premium_retail', 'electric_bikes', 'fashion', 'beauty', 'fitness', 'marketplace', 'restaurant'],
        pageIntents: ['ecommerce_home', 'storefront_home'],
        conversionRoles: ['sales', 'product_discovery'],
        requiredModules: ['ecommerce'],
        dataRequirements: [data('productsCount', 'Products or reviewable product drafts', 'ecommerceBlueprint.starterProducts', 1)],
        minDataRequired: { productsCount: 1 },
        allowedSources: commerceSources,
        requiredFeature: 'ecommerceEnabled',
        fallbackComponentId: 'shopCTA',
        dataAccess: access(['products', 'prices', 'categories', 'storefront_routes'], 'ecommerce-engine'),
        renderTargets: { websiteSection: 'featuredProducts', websiteEcommerceBlock: 'featuredProducts', storefrontSectionType: 'featuredProducts' },
        selectionGuidance: ['Use only when Ecommerce Engine has real products or reviewable starter product drafts.'],
        antiPatterns: ['Do not show products, prices, inventory, discounts, or ratings as real unless they came from Ecommerce Engine or merchant input.'],
    }),
    entry({
        id: 'productCarousel',
        label: 'Product Carousel',
        description: 'Scrollable product discovery block for enough products to justify a carousel.',
        family: 'website_ecommerce_block',
        implementationStatus: 'metadata_only',
        visualSupportNotes: 'Creates website ecommerce block metadata with carousel intent; existing visual section is featuredProducts.',
        compatibleIndustries: ['ecommerce', 'premium_retail', 'fashion', 'beauty', 'fitness', 'marketplace'],
        pageIntents: ['ecommerce_home', 'storefront_home'],
        conversionRoles: ['sales', 'product_discovery'],
        requiredModules: ['ecommerce'],
        dataRequirements: [data('productsCount', 'Products or reviewable product drafts', 'ecommerceBlueprint.starterProducts', 4)],
        minDataRequired: { productsCount: 4 },
        allowedSources: commerceSources,
        requiredFeature: 'ecommerceEnabled',
        fallbackComponentId: 'featuredProducts',
        dataAccess: access(['products', 'prices', 'storefront_routes'], 'ecommerce-engine'),
        renderTargets: { websiteSection: 'featuredProducts', websiteEcommerceBlock: 'productCarousel', storefrontSectionType: 'featuredProducts' },
    }),
    entry({
        id: 'categoryShowcase',
        label: 'Category Showcase',
        description: 'Website ecommerce block for product categories or collections.',
        family: 'website_ecommerce_block',
        compatibleIndustries: ['ecommerce', 'premium_retail', 'electric_bikes', 'marketplace', 'restaurant'],
        pageIntents: ['ecommerce_home', 'storefront_home', 'product_collection'],
        conversionRoles: ['catalog_discovery', 'sales'],
        requiredModules: ['ecommerce'],
        dataRequirements: [data('categoriesCount', 'Categories or collections', 'ecommerceBlueprint.productCategories', 1)],
        minDataRequired: { categoriesCount: 1 },
        allowedSources: commerceSources,
        requiredFeature: 'ecommerceEnabled',
        fallbackComponentId: 'shopCTA',
        dataAccess: access(['categories', 'collections', 'storefront_routes'], 'ecommerce-engine'),
        renderTargets: { websiteSection: 'categoryGrid', websiteEcommerceBlock: 'categoryShowcase', storefrontSectionType: 'categoryGrid' },
    }),
    entry({
        id: 'shopCTA',
        label: 'Shop CTA',
        description: 'Fallback website CTA that routes into storefront without implying catalog readiness.',
        family: 'website_ecommerce_block',
        compatibleIndustries: ['ecommerce', 'premium_retail', 'marketplace', 'restaurant', 'services'],
        pageIntents: ['ecommerce_home', 'storefront_home', 'service_landing'],
        conversionRoles: ['sales', 'navigation'],
        optionalModules: ['ecommerce'],
        allowedSources: commerceSources,
        dataAccess: access(['storefront_routes'], 'ecommerce-engine'),
        renderTargets: { websiteSection: 'cta', websiteEcommerceBlock: 'shopCTA', storefrontSectionType: 'shopCTA' },
        selectionGuidance: ['Use as fallback when ecommerce is enabled but catalog data is incomplete.'],
    }),
    entry({
        id: 'saleCountdown',
        label: 'Sale Countdown',
        description: 'Promotion countdown block tied to a real merchant-approved promotion.',
        family: 'website_ecommerce_block',
        compatibleIndustries: ['ecommerce', 'retail', 'fashion', 'beauty', 'fitness'],
        pageIntents: ['ecommerce_home', 'storefront_home'],
        conversionRoles: ['sales'],
        requiredModules: ['ecommerce'],
        dataRequirements: [data('hasMerchantApprovedPromotion', 'Merchant-approved promotion', 'ecommerceBlueprint.discounts', 1, true, true)],
        allowedSources: commerceSources,
        requiredFeature: 'ecommerceEnabled',
        fallbackComponentId: 'shopCTA',
        dataAccess: access(['discounts', 'storefront_routes'], 'ecommerce-engine'),
        renderTargets: { websiteSection: 'saleCountdown', websiteEcommerceBlock: 'promoBanner', storefrontSectionType: 'saleCountdown' },
        antiPatterns: ['Do not create active discounts, false urgency, or countdown timers without merchant approval.'],
    }),
    entry({
        id: 'trustBadges',
        label: 'Trust Badges',
        description: 'Compact trust cues for shipping, payment, local service, guarantees, certifications, or safety.',
        family: 'website_content',
        compatibleIndustries: ['all', 'ecommerce', 'services', 'local_business', 'restaurant', 'real_estate'],
        pageIntents: ['website_home', 'service_landing', 'ecommerce_home', 'restaurant_home', 'real_estate_home', 'local_business_home'],
        conversionRoles: ['trust'],
        renderTargets: { websiteSection: 'trustBadges', storefrontSectionType: 'trustBadges' },
        antiPatterns: ['Do not imply certifications, guarantees, reviews, payment readiness, or shipping policies that were not provided.'],
    }),
    entry({
        id: 'productHero',
        label: 'Product Hero',
        description: 'Product detail or product-led hero for storefront/product pages.',
        family: 'product_page_section',
        compatibleBuilders: ['storefront', 'ecommerce'],
        compatibleIndustries: ['ecommerce', 'premium_retail', 'electric_bikes', 'fashion', 'fitness', 'beauty'],
        pageIntents: ['product_detail', 'storefront_home', 'ecommerce_home'],
        conversionRoles: ['sales', 'product_discovery'],
        requiredModules: ['ecommerce'],
        allowedSources: commerceSources,
        dataAccess: access(['products', 'prices', 'media'], 'ecommerce-engine', 'storefront-builder'),
        renderTargets: { storefrontSectionType: 'productHero' },
    }),
    entry({
        id: 'collectionBanner',
        label: 'Collection Banner',
        description: 'Collection/category header for storefront collection pages.',
        family: 'collection_section',
        compatibleBuilders: ['storefront', 'ecommerce'],
        compatibleIndustries: ['ecommerce', 'marketplace', 'premium_retail', 'fashion', 'fitness'],
        pageIntents: ['product_collection', 'storefront_home'],
        conversionRoles: ['catalog_discovery'],
        requiredModules: ['ecommerce'],
        allowedSources: commerceSources,
        dataAccess: access(['collections', 'categories', 'storefront_routes'], 'ecommerce-engine', 'storefront-builder'),
        renderTargets: { storefrontSectionType: 'collectionBanner' },
    }),
    entry({
        id: 'restaurantMenu',
        label: 'Restaurant Menu',
        description: 'Restaurant menu, catering, gift card, or featured dishes section.',
        family: 'restaurant_block',
        compatibleIndustries: ['restaurant', 'food'],
        pageIntents: ['restaurant_home'],
        conversionRoles: ['education', 'sales'],
        requiredModules: ['restaurant'],
        dataRequirements: [data('menuItemsCount', 'Menu or offer signals', 'restaurantBlueprint.menuSignals', 1, false)],
        renderTargets: { websiteSection: 'menu' },
    }),
    entry({
        id: 'restaurantReservation',
        label: 'Restaurant Reservation',
        description: 'Reservation or catering inquiry block for restaurant businesses.',
        family: 'restaurant_block',
        compatibleIndustries: ['restaurant', 'food'],
        pageIntents: ['restaurant_home', 'appointment_landing'],
        conversionRoles: ['booking', 'lead_capture'],
        requiredModules: ['restaurantReservations'],
        fallbackComponentId: 'leadForm',
        renderTargets: { websiteSection: 'restaurantReservation' },
    }),
    entry({
        id: 'restaurantLocation',
        label: 'Restaurant Location',
        description: 'Location, hours, neighborhood, and contact block for restaurants.',
        family: 'restaurant_block',
        compatibleIndustries: ['restaurant', 'food', 'local_business'],
        pageIntents: ['restaurant_home', 'local_business_home'],
        conversionRoles: ['trust', 'lead_capture'],
        renderTargets: { websiteSection: 'map' },
    }),
    entry({
        id: 'realEstateListings',
        label: 'Real Estate Listings',
        description: 'Property listings, listing teasers, or draft listing directory entry point.',
        family: 'real_estate_block',
        compatibleIndustries: ['real_estate'],
        pageIntents: ['real_estate_home'],
        conversionRoles: ['lead_capture', 'catalog_discovery'],
        requiredModules: ['realEstate'],
        dataRequirements: [data('listingsCount', 'Listings or listing drafts', 'realEstateBlueprint.listingTypes', 1, false)],
        renderTargets: { websiteSection: 'realEstateListings' },
    }),
    entry({
        id: 'propertySearch',
        label: 'Property Search',
        description: 'Search or filter entry point for real estate visitors.',
        family: 'real_estate_block',
        implementationStatus: 'planned',
        visualSupportNotes: 'Property search is represented as intent metadata; the homepage renderer must not mount propertyDirectory as a search section yet.',
        compatibleIndustries: ['real_estate'],
        pageIntents: ['real_estate_home'],
        conversionRoles: ['lead_capture', 'catalog_discovery'],
        requiredModules: ['realEstate'],
        renderTargets: { websiteSection: 'propertyDirectory' },
    }),
    entry({
        id: 'neighborhoods',
        label: 'Neighborhoods',
        description: 'Neighborhood, market, or buyer/seller education section for real estate.',
        family: 'real_estate_block',
        implementationStatus: 'metadata_only',
        visualSupportNotes: 'Maps to features metadata until dedicated neighborhood cards are implemented.',
        compatibleIndustries: ['real_estate'],
        pageIntents: ['real_estate_home'],
        conversionRoles: ['education', 'trust'],
        requiredModules: ['realEstate'],
        renderTargets: { websiteSection: 'features' },
    }),
    entry({
        id: 'footer',
        label: 'Footer',
        description: 'Global footer with navigation, contact, legal, social, and optional newsletter links.',
        family: 'global_layout',
        compatibleBuilders: ['website', 'storefront'],
        pageIntents: ['website_home', 'service_landing', 'ecommerce_home', 'storefront_home', 'restaurant_home', 'real_estate_home', 'portfolio_home', 'gallery_home', 'ai_saas_landing'],
        conversionRoles: ['navigation', 'compliance'],
        recommendedPosition: 'footer',
        mobilePriority: 'medium',
        renderTargets: { websiteSection: 'footer', storefrontSectionType: 'storeFooter' },
    }),
    entry({
        id: 'storefrontFeaturedProducts',
        label: 'Storefront Featured Products',
        description: 'Storefront-only featured product section controlled by Storefront Builder.',
        family: 'storefront_section',
        compatibleBuilders: ['storefront'],
        compatibleIndustries: ['ecommerce', 'premium_retail', 'marketplace'],
        pageIntents: ['storefront_home'],
        conversionRoles: ['sales', 'product_discovery'],
        requiredModules: ['ecommerce'],
        allowedSources: commerceSources,
        dataAccess: access(['products', 'prices'], 'ecommerce-engine', 'storefront-builder'),
        renderTargets: { storefrontSectionType: 'featuredProducts' },
    }),
    entry({
        id: 'storefrontCategoryGrid',
        label: 'Storefront Category Grid',
        description: 'Storefront-only category section controlled by Storefront Builder.',
        family: 'storefront_section',
        compatibleBuilders: ['storefront'],
        compatibleIndustries: ['ecommerce', 'marketplace'],
        pageIntents: ['storefront_home', 'product_collection'],
        conversionRoles: ['catalog_discovery'],
        requiredModules: ['ecommerce'],
        allowedSources: commerceSources,
        dataAccess: access(['categories', 'collections'], 'ecommerce-engine', 'storefront-builder'),
        renderTargets: { storefrontSectionType: 'categoryGrid' },
    }),
];

export const componentRegistryById: Record<ComponentId, ComponentRegistryEntry> = componentRegistry.reduce((acc, component) => {
    acc[component.id] = component;
    return acc;
}, {} as Record<ComponentId, ComponentRegistryEntry>);

export const isComponentId = (value: unknown): value is ComponentId => (
    typeof value === 'string' && value in componentRegistryById
);

export const getComponentDefinition = (componentId: ComponentId | string): ComponentRegistryEntry | undefined => (
    isComponentId(componentId) ? componentRegistryById[componentId] : undefined
);

export const getComponentsForBuilder = (builder: ComponentBuilder): ComponentRegistryEntry[] => (
    componentRegistry.filter(component => component.compatibleBuilders.includes(builder))
);

export const getComponentsByFamily = (family: ComponentRegistryFamily): ComponentRegistryEntry[] => (
    componentRegistry.filter(component => component.family === family)
);
