import type { PageSection } from '../types/ui';
import type { PlanFeatures, SubscriptionPlanId } from '../types/subscription';
import type { PlatformServiceId } from '../types/serviceAvailability';

export type ModuleKind =
    | 'website-section'
    | 'website-ecommerce-block'
    | 'storefront-section'
    | 'engine'
    | 'integration'
    | 'automation';

export type ModuleOwnerSystem =
    | 'ai-studio'
    | 'website-builder'
    | 'storefront-builder'
    | 'ecommerce-admin'
    | 'ecommerce-engine'
    | 'chatbot-engine'
    | 'crm'
    | 'email-marketing'
    | 'media-ai'
    | 'bio-page-engine'
    | 'appointments-engine'
    | 'restaurant-engine'
    | 'real-estate-engine'
    | 'finance'
    | 'analytics'
    | 'automation-engine';

export type CanonicalSystemId =
    | 'ecommerce'
    | 'crm'
    | 'emailMarketing'
    | 'chatbot'
    | 'appointments'
    | 'restaurants'
    | 'realEstate'
    | 'finance'
    | 'analytics'
    | 'bioPage'
    | 'media';

export interface ModuleRegistryItem {
    id: string;
    label: string;
    moduleKind: ModuleKind;
    ownerSystem: ModuleOwnerSystem;
    canonicalSystem?: CanonicalSystemId;
    description: string;
    requiredPlan?: SubscriptionPlanId;
    requiredFeature?: keyof PlanFeatures;
    requiredService?: PlatformServiceId;
    gatingReason?: string;
    compatibleIndustries: string[];
    requiredModules?: string[];
    optionalModules?: string[];
    unsupportedModules?: string[];
    editableBy: ModuleOwnerSystem[];
    readsFrom?: CanonicalSystemId[];
    writesTo?: CanonicalSystemId[];
    sections?: PageSection[];
}

export interface ModuleRegistryAccessContext {
    currentPlan?: SubscriptionPlanId;
    hasPlanFeature?: (feature: keyof PlanFeatures) => boolean;
    canAccessService?: (service: PlatformServiceId) => boolean;
}

const PLAN_RANK: Record<SubscriptionPlanId, number> = {
    free: 0,
    hobby: 1,
    starter: 2,
    individual: 3,
    pro: 4,
    agency_starter: 5,
    agency: 6,
    agency_pro: 7,
    agency_plus: 8,
    agency_scale: 9,
    enterprise: 10,
};

const ecommerceGate = {
    requiredService: 'ecommerce' as const,
    requiredFeature: 'ecommerceEnabled' as const,
    gatingReason: 'Requires ecommerce service availability and an ecommerce-enabled plan.',
};

export const quimeraModuleRegistry: ModuleRegistryItem[] = [
    {
        id: 'ai-business-blueprint',
        label: 'AI Business Blueprint',
        moduleKind: 'engine',
        ownerSystem: 'ai-studio',
        canonicalSystem: 'analytics',
        description: 'Central project contract generated by AI Studio and used to coordinate connected modules.',
        compatibleIndustries: ['all'],
        editableBy: ['ai-studio'],
        writesTo: ['ecommerce', 'crm', 'emailMarketing', 'chatbot', 'appointments', 'restaurants', 'realEstate', 'finance', 'analytics', 'media'],
    },
    {
        id: 'website-builder',
        label: 'Website Builder',
        moduleKind: 'engine',
        ownerSystem: 'website-builder',
        description: 'Edits website content, layout, conversion modules, and ecommerce display blocks.',
        compatibleIndustries: ['all'],
        editableBy: ['website-builder', 'ai-studio'],
        readsFrom: ['ecommerce', 'crm', 'chatbot', 'appointments', 'restaurants', 'realEstate'],
    },
    {
        id: 'bio-page-engine',
        label: 'Bio Page Engine',
        moduleKind: 'engine',
        ownerSystem: 'bio-page-engine',
        canonicalSystem: 'bioPage',
        description: 'Mobile-first link-in-bio funnel engine for creator profiles, links, shop blocks, booking, leads, email subscribe, ChatCore, analytics, QR, SEO, and AI-generated drafts.',
        compatibleIndustries: ['all', 'creator', 'portfolio', 'ecommerce', 'restaurant', 'real-estate', 'services', 'fitness', 'beauty', 'local_business'],
        editableBy: ['bio-page-engine', 'ai-studio', 'website-builder'],
        readsFrom: ['ecommerce', 'appointments', 'crm', 'emailMarketing', 'chatbot', 'media', 'analytics'],
        writesTo: ['crm', 'emailMarketing', 'analytics', 'appointments'],
    },
    {
        id: 'storefront-builder',
        label: 'Storefront Builder',
        moduleKind: 'engine',
        ownerSystem: 'storefront-builder',
        description: 'Edits storefront presentation, templates, product-card style, cart visuals, and checkout visuals.',
        compatibleIndustries: ['ecommerce', 'retail', 'fashion', 'fitness', 'food', 'beauty', 'digital'],
        editableBy: ['storefront-builder', 'ai-studio'],
        readsFrom: ['ecommerce'],
        ...ecommerceGate,
    },
    {
        id: 'ecommerce-engine',
        label: 'Ecommerce Engine',
        moduleKind: 'engine',
        ownerSystem: 'ecommerce-engine',
        canonicalSystem: 'ecommerce',
        description: 'Canonical system for products, variants, prices, inventory, carts, checkout, orders, discounts, shipping, taxes, and customers.',
        compatibleIndustries: ['ecommerce', 'retail', 'fashion', 'fitness', 'food', 'restaurant', 'real-estate', 'services', 'digital'],
        editableBy: ['ecommerce-admin', 'ai-studio'],
        writesTo: ['crm', 'emailMarketing', 'finance', 'analytics', 'chatbot'],
        ...ecommerceGate,
    },
    {
        id: 'website-featured-products-block',
        label: 'Website Featured Products Block',
        moduleKind: 'website-ecommerce-block',
        ownerSystem: 'website-builder',
        canonicalSystem: 'ecommerce',
        description: 'Website block that displays products from the Ecommerce Engine and routes shoppers to storefront/product pages.',
        compatibleIndustries: ['ecommerce', 'retail', 'fashion', 'fitness', 'food', 'beauty', 'digital'],
        editableBy: ['website-builder'],
        readsFrom: ['ecommerce'],
        ...ecommerceGate,
    },
    {
        id: 'storefront-home-sections',
        label: 'Storefront Home Sections',
        moduleKind: 'storefront-section',
        ownerSystem: 'storefront-builder',
        canonicalSystem: 'ecommerce',
        description: 'Storefront sections such as hero, collections, product grid, promo strips, trust badges, reviews, newsletter, and footer.',
        compatibleIndustries: ['ecommerce', 'retail', 'fashion', 'fitness', 'food', 'beauty', 'digital'],
        editableBy: ['storefront-builder'],
        readsFrom: ['ecommerce', 'emailMarketing'],
        sections: ['announcementBar', 'productHero', 'featuredProducts', 'categoryGrid', 'trustBadges', 'productReviews'],
        ...ecommerceGate,
    },
    {
        id: 'crm-leads',
        label: 'Leads / CRM',
        moduleKind: 'integration',
        ownerSystem: 'crm',
        canonicalSystem: 'crm',
        description: 'Canonical system for leads, lead tags, and lead activity timelines.',
        requiredService: 'crm',
        requiredFeature: 'crmEnabled',
        gatingReason: 'Requires CRM service availability and a CRM-enabled plan.',
        compatibleIndustries: ['all'],
        editableBy: ['crm', 'ai-studio'],
        readsFrom: ['ecommerce', 'chatbot', 'appointments', 'realEstate'],
        writesTo: ['emailMarketing', 'analytics'],
    },
    {
        id: 'email-marketing',
        label: 'Email Marketing',
        moduleKind: 'integration',
        ownerSystem: 'email-marketing',
        canonicalSystem: 'emailMarketing',
        description: 'Canonical system for campaigns, audiences, automations, transactional flow drafts, and email logs.',
        requiredService: 'emailMarketing',
        requiredFeature: 'emailMarketing',
        gatingReason: 'Requires email marketing service availability and plan access.',
        compatibleIndustries: ['all'],
        editableBy: ['email-marketing', 'ai-studio'],
        readsFrom: ['ecommerce', 'crm', 'appointments', 'restaurants', 'realEstate'],
        writesTo: ['analytics'],
    },
    {
        id: 'chatbot-engine',
        label: 'Chatbot Engine',
        moduleKind: 'integration',
        ownerSystem: 'chatbot-engine',
        canonicalSystem: 'chatbot',
        description: 'Canonical system for chatbot configuration, FAQs, knowledge documents, knowledge links, and product/policy knowledge sources.',
        requiredService: 'chatbot',
        requiredFeature: 'chatbotEnabled',
        gatingReason: 'Requires chatbot service availability and plan access.',
        compatibleIndustries: ['all'],
        editableBy: ['chatbot-engine', 'ai-studio'],
        readsFrom: ['ecommerce', 'crm', 'appointments', 'restaurants', 'realEstate'],
        writesTo: ['crm', 'analytics'],
    },
    {
        id: 'appointments-engine',
        label: 'Appointments Engine',
        moduleKind: 'integration',
        ownerSystem: 'appointments-engine',
        canonicalSystem: 'appointments',
        description: 'Canonical system for appointments, paid consultations, deposits, classes, and service bookings.',
        requiredService: 'appointments',
        gatingReason: 'Requires appointments service availability.',
        compatibleIndustries: ['services', 'fitness', 'wellness', 'healthcare', 'beauty', 'consulting', 'education'],
        editableBy: ['appointments-engine', 'ai-studio'],
        readsFrom: ['crm', 'ecommerce'],
        writesTo: ['crm', 'emailMarketing', 'analytics'],
    },
    {
        id: 'restaurant-engine',
        label: 'Restaurant Engine',
        moduleKind: 'integration',
        ownerSystem: 'restaurant-engine',
        canonicalSystem: 'restaurants',
        description: 'Canonical system for menus, hours, locations, reservations, restaurant analytics, and restaurant ecommerce offers.',
        requiredService: 'restaurants',
        gatingReason: 'Requires restaurants service availability.',
        compatibleIndustries: ['restaurant', 'cafe', 'food', 'bar', 'bakery', 'catering', 'steakhouse', 'sushi', 'pizza', 'brunch', 'food-truck'],
        editableBy: ['restaurant-engine', 'ai-studio'],
        readsFrom: ['ecommerce', 'emailMarketing'],
        writesTo: ['crm', 'emailMarketing', 'analytics'],
    },
    {
        id: 'real-estate-engine',
        label: 'Real Estate Engine',
        moduleKind: 'integration',
        ownerSystem: 'real-estate-engine',
        canonicalSystem: 'realEstate',
        description: 'Canonical system for listings, property leads, campaigns, open houses, and real estate digital products.',
        requiredService: 'realEstate',
        requiredFeature: 'realEstateModule',
        gatingReason: 'Requires real estate service availability and plan access.',
        compatibleIndustries: ['real-estate'],
        editableBy: ['real-estate-engine', 'ai-studio'],
        readsFrom: ['ecommerce', 'crm'],
        writesTo: ['crm', 'emailMarketing', 'analytics'],
    },
    {
        id: 'finance',
        label: 'Finance',
        moduleKind: 'integration',
        ownerSystem: 'finance',
        canonicalSystem: 'finance',
        description: 'Canonical system for revenue, refunds, fees, taxes, payouts, and financial reporting.',
        requiredService: 'finance',
        gatingReason: 'Requires finance service availability.',
        compatibleIndustries: ['all'],
        editableBy: ['finance'],
        readsFrom: ['ecommerce', 'appointments', 'restaurants', 'realEstate'],
        writesTo: ['analytics'],
    },
];

export function canAccessModuleRegistryItem(item: ModuleRegistryItem, access: ModuleRegistryAccessContext = {}): boolean {
    if (item.requiredPlan && access.currentPlan && PLAN_RANK[access.currentPlan] < PLAN_RANK[item.requiredPlan]) return false;
    if (item.requiredService && (!access.canAccessService || !access.canAccessService(item.requiredService))) return false;
    if (item.requiredFeature && (!access.hasPlanFeature || !access.hasPlanFeature(item.requiredFeature))) return false;
    return true;
}

export function getAccessibleModuleRegistry(access: ModuleRegistryAccessContext = {}): ModuleRegistryItem[] {
    return quimeraModuleRegistry.filter(item => canAccessModuleRegistryItem(item, access));
}

export function getModuleRegistryItem(id: string): ModuleRegistryItem | undefined {
    return quimeraModuleRegistry.find(item => item.id === id);
}

export function getModulesByCanonicalSystem(system: CanonicalSystemId): ModuleRegistryItem[] {
    return quimeraModuleRegistry.filter(item => item.canonicalSystem === system || item.readsFrom?.includes(system) || item.writesTo?.includes(system));
}
